'use client';
import NumberInput from './NumberInput';
import {useRef,useState} from 'react';
import {extent,emptyAccess,siteEntrances,withEntrances,type SiteAccess,type XY} from './planning';
export default function AccessCanvas({boundary,access=emptyAccess(),onChange}:{boundary:XY[];access?:SiteAccess;onChange:(a:SiteAccess)=>void}){
 const [mode,setMode]=useState<'entrance'|'road'>('entrance'),[path,setPath]=useState<XY[]>([]),[width,setWidth]=useState(9),[selected,setSelected]=useState<string|null>(null),[zoom,setZoom]=useState(1),[offset,setOffset]=useState({x:0,y:0}),[pan,setPan]=useState(false);
 const svg=useRef<SVGSVGElement>(null),drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null),b=extent(boundary),entrances=siteEntrances(access),max=Math.max(b.w,b.h);
 const position=(e:React.PointerEvent)=>{const m=svg.current?.getScreenCTM()?.inverse();if(!m)return{x:0,y:0};const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m);return{x:p.x,y:p.y};};
 function place(edge:number,point?:XY){if(pan)return;const p=boundary[edge],q=boundary[(edge+1)%boundary.length],dx=q.x-p.x,dy=q.y-p.y,t=point?Math.max(.03,Math.min(.97,((point.x-p.x)*dx+(point.y-p.y)*dy)/(dx*dx+dy*dy))):.5;
  const id=selected||Array.from({length:13},(_,i)=>`entry-${i+1}`).find(id=>!entrances.some(e=>e.id===id))!,existing=entrances.find(e=>e.id===selected);if(!existing&&entrances.length>=12)return;
  const next={id,edge,t,width:existing?.width??null,entranceWidth:existing?.entranceWidth??9};onChange(withEntrances(access,existing?entrances.map(e=>e.id===id?next:e):[...entrances,next]));setSelected(null);
 }
 return <section className="ws-access"><span className="ws-eyebrow">WHERE CAN PEOPLE ENTER?</span><h2>Tap the boundary to add an entrance.</h2><p className="ws-helper">Each entrance automatically marks that side as road-facing. Add as many access points as your project needs. Entrance opening is the width of your gate from the outside road into this site; external road width is a separate measurement.</p>
 <div className="ws-access-toolbar"><button className={mode==='entrance'?'ws-primary':''} onClick={()=>{setMode('entrance');setSelected(null);setPan(false);}}>Add entrance</button><button onClick={()=>setPan(v=>!v)} aria-pressed={pan}>{pan?'Stop moving map':'Move map'}</button><button aria-label="Zoom access map in" onClick={()=>setZoom(v=>Math.min(5,v+.5))}>+</button><button aria-label="Zoom access map out" onClick={()=>setZoom(v=>Math.max(1,v-.5))}>−</button><button onClick={()=>{setZoom(1);setOffset({x:0,y:0});}}>Fit</button></div>
 {selected&&<p className="ws-helper">Tap a new boundary position to move the selected entrance.</p>}
 <svg ref={svg} aria-label="Entrance map" viewBox={`${b.w/2+offset.x-(b.w+50)/zoom/2} ${b.h/2+offset.y-(b.h+50)/zoom/2} ${(b.w+50)/zoom} ${(b.h+50)/zoom}`} onPointerDown={e=>{if(pan){drag.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};e.currentTarget.setPointerCapture(e.pointerId);}else if(mode==='road')setPath([...path,position(e)]);}} onPointerMove={e=>{if(!drag.current)return;const scale=svg.current?.getScreenCTM()?.a||1;setOffset({x:drag.current.ox-(e.clientX-drag.current.x)/scale,y:drag.current.oy-(e.clientY-drag.current.y)/scale});}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 <polygon points={boundary.map(p=>`${p.x},${p.y}`).join(' ')} fill="#eaf0e3"/>
 {access.roads.map(r=><polyline key={r.id} points={r.points.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#8a9aa5" strokeWidth={r.width} opacity=".65"/>)}
 {boundary.map((p,i)=>{const q=boundary[(i+1)%boundary.length],active=entrances.some(e=>e.edge===i);return <g key={i}><line x1={p.x} y1={p.y} x2={q.x} y2={q.y} stroke={active?'#367b9a':'#76866b'} strokeWidth={max/130}/><line role="button" tabIndex={0} aria-label={`Add entrance on edge ${i+1}`} x1={p.x} y1={p.y} x2={q.x} y2={q.y} stroke="transparent" strokeWidth={max/35/zoom} style={{cursor:'pointer'}} onPointerDown={e=>{if(mode==='road'||pan)return;e.stopPropagation();place(i,position(e));}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();place(i);}}}/></g>;})}
 {entrances.map((e,i)=>{const a=boundary[e.edge],z=boundary[(e.edge+1)%boundary.length],x=a.x+(z.x-a.x)*e.t,y=a.y+(z.y-a.y)*e.t;const length=Math.hypot(z.x-a.x,z.y-a.y),half=(e.entranceWidth??9)/2;return <g key={e.id} pointerEvents="none"><line x1={x-(z.x-a.x)/length*half} y1={y-(z.y-a.y)/length*half} x2={x+(z.x-a.x)/length*half} y2={y+(z.y-a.y)/length*half} stroke="#b57f35" strokeWidth="2"/><circle cx={x} cy={y} r={max/45/zoom} fill="#b57f35" stroke="white"/><text x={x} y={y+max/90/zoom} textAnchor="middle" fontSize={max/40/zoom} fill="white">{i+1}</text><text x={x} y={y+max/18/zoom} textAnchor="middle" fontSize={max/50/zoom}>Entrance {i+1}</text></g>;})}
 {path.length>0&&<polyline points={path.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#b78744" strokeWidth={width} opacity=".6"/>}
 </svg>
 <div className="ws-entrance-list">{entrances.length===0&&<p>No entrances yet. Tap any outside edge above.</p>}{entrances.map((e,i)=><div className="ws-entrance-row" key={e.id}><b>Entrance {i+1}</b><label className="ws-field">Entrance opening (m)<NumberInput min={3} max={30} value={e.entranceWidth??9} onCommit={entranceWidth=>onChange(withEntrances(access,entrances.map(q=>q.id===e.id?{...q,entranceWidth}:q)))}/></label><label className="ws-field">External road width (optional, m)<input type="number" min="1" max="100" placeholder="Unknown" value={e.width??''} onChange={event=>onChange(withEntrances(access,entrances.map(q=>q.id===e.id?{...q,width:event.target.value?Math.max(1,Math.min(100,Number(event.target.value))):null}:q)))}/></label><button onClick={()=>{setSelected(e.id);setMode('entrance');setPan(false);}}>Move</button><button onClick={()=>{onChange(withEntrances(access,entrances.filter(q=>q.id!==e.id)));setSelected(null);}}>Remove</button></div>)}</div>
 <details className="ws-details"><summary>North direction (optional)</summary><label className="ws-field">Do you know north?<select value={access.northAngle==null?'unknown':'known'} onChange={e=>onChange({...access,northAngle:e.target.value==='unknown'?null:0})}><option value="unknown">I don’t know</option><option value="known">Set from my survey</option></select></label>{access.northAngle!=null&&<><div className="ws-north-preview"><span style={{transform:`rotate(${access.northAngle}deg)`}}>↑</span><b>N</b></div><label className="ws-field">Rotate north arrow · {access.northAngle}°<input type="range" min="0" max="359" value={access.northAngle} onChange={e=>onChange({...access,northAngle:Number(e.target.value)})}/></label></>}<p className="ws-helper">Unknown north is fine. Plot-facing directions remain unknown until you set it. Entrance position alone does not tell us north.</p></details>
 <details className="ws-details"><summary>Existing road crossing the land (optional)</summary><p className="ws-helper">Use only for an existing road inside the parcel. The planner generates new internal roads automatically.</p><button onClick={()=>{setMode('road');setPan(false);}}>Draw existing road</button>{mode==='road'&&<div><label className="ws-field">Existing road width (m)<input type="number" min="1" max="100" value={width} onChange={e=>setWidth(Math.max(1,Math.min(100,Number(e.target.value))))}/></label><button onClick={()=>setPath(path.slice(0,-1))}>Undo road point</button><button disabled={path.length<2} onClick={()=>{onChange({...access,roads:[...access.roads,{id:String(Date.now()),points:path,width}]});setPath([]);setMode('entrance');}}>Save existing road</button></div>}{access.roads.map((r,i)=><div key={r.id}>Existing road {i+1} · {r.width} m <button onClick={()=>onChange({...access,roads:access.roads.filter(q=>q.id!==r.id)})}>Remove</button></div>)}</details>
 </section>;
}
