import {residualReview,plotMixReport,objectiveLabels,currency,type Concept,type Brief} from './planning';
export default function ConceptExplanation({concept:c,brief}:{concept:Concept;brief:Brief}){
 const mix=plotMixReport(c),missing=c.checks.filter(v=>v.state==='fail');
 return <details className="ws-details ws-explanation"><summary>Why this layout? · {objectiveLabels[brief.objective||'area']}</summary><p>{c.strategy}</p><div className="ws-explanation-metrics"><span><b>{c.efficiency.toFixed(1)}%</b> saleable land</span><span><b>{(c.roadsArea/c.area*100).toFixed(1)}%</b> roads</span><span><b>{currency(c.infra)}</b> infrastructure</span><span><b>{currency(c.profit)}</b> estimated profit</span></div>
 <h3>Your plot mix, checked</h3><p className="ws-helper">Residential and EWS plots only. Dimensions must match within 0.025 m; commercial plots are accounted for separately.</p><div className="ws-table-scroll"><table><thead><tr><th>Size (ft)</th><th>Minimum</th><th>Delivered</th><th>Share / target</th><th>Result</th></tr></thead><tbody>{mix.rows.map(r=><tr key={`${r.width}x${r.depth}`}><td>{r.width} × {r.depth}</td><td>{r.minCount}</td><td>{r.actual}</td><td>{r.share.toFixed(0)}% / {r.targetPercent?`${r.targetPercent}%`:'Flexible'}</td><td>{r.shortfall?`${r.shortfall} missing`:'Minimum met'}</td></tr>)}</tbody></table></div><p><b>{mix.extras.length} adjusted or additional plots.</b> {brief.allowExtraSizes===false?'No new off-size residential plots are allowed. Locked or manually assigned plots may differ.':'These use your permission to adapt sizes.'}</p>{mix.extras.length>0&&<details><summary>See additional plot sizes</summary><p className="ws-helper">{mix.extras.map(l=>`${l.id}: ${(l.w/.3048).toFixed(1)} × ${(l.h/.3048).toFixed(1)} ft${l.shape==='irregular'?' (irregular bounding dimensions)':''}`).join(' · ')}</p></details>}
 <h3>Road widths actually used</h3><p className="ws-helper">Requested range: {brief.road}–{brief.roadMax} m. Minimum is a lower limit, not a promise of an exact width. Length is measured on clipped full-width streets; only a wider main street splits a secondary run. Extendable streets {brief.extendableRoads?'use a 9 m baseline floor':'are not assumed; confirm classification with the consultant'}.</p><div className="ws-table-scroll"><table><thead><tr><th>Street</th><th>Run length</th><th>Applied</th><th>Baseline</th><th>Width check</th></tr></thead><tbody>{c.roadSchedule?.map((r,i)=><tr key={i}><td>{r.name}</td><td>{r.length.toFixed(1)} m</td><td>{r.width.toFixed(1)} m</td><td>{r.required.toFixed(1)} m</td><td>{r.width+.001<Math.max(r.required,brief.road)?'Too narrow':r.width>brief.roadMax+.001?'Above maximum':r.width>brief.road+.001?'Wider: baseline / main / access':'Requested minimum'}</td></tr>)}</tbody></table></div><p className="ws-helper">Sourced planning baseline only. The approval consultant must verify current rules, road classification, junctions, turning and access rights.</p>
 <h3>Park & remaining land</h3><p>{c.parkDecision} {c.searchCount||0} arrangements tested for this option. This is a bounded search, not proof of a global optimum.</p><p><b>{c.unallocated.toFixed(0)} m² remains unallocated.</b> The planner does not label these pockets as saleable to improve a score.</p><div className="ws-table-scroll"><table><thead><tr><th>Remaining-land diagnostic</th><th>Pockets</th><th>Area</th></tr></thead><tbody>{residualReview(c).map(r=><tr key={r.reason}><td>{r.reason}</td><td>{r.pockets}</td><td>{r.area.toFixed(0)} m²</td></tr>)}</tbody></table></div><p className="ws-helper">These checks explain known limits. An unresolved pocket may still be recoverable through a different road arrangement or manual design.</p><p className="ws-helper">Allocated land includes roads, reserves, protected land and manually assigned utilities. It is not the same as saleable or independently verified usable land. Utility assignments still require service and clearance checks.</p>{missing.length>0&&<div className="ws-rule-note"><b>Requirements still unresolved</b><ul>{missing.map(check=><li key={check.name}>{check.name}: {check.actual}. Required: {check.requirement}.</li>)}</ul></div>}
 </details>;
}
