import {plotMixReport,objectiveLabels,corners,lotPoints,plotValue,clipToBox,triangulate, saleLots,SQFT,FT,type Concept,type Exclusion,type Project} from './planning';
export function saveFile(name:string,body:string,type='application/json'){const u=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export function asCSV(rows:(string|number)[][]){return rows.map(row=>row.map(cell=>`"${String(cell).replace(/"/g,'""')}"`).join(',')).join('\r\n');}
export function inventoryCSV(c:Concept,status:Project['inventory']){return asCSV([['Concept','Plot','Type','Width m','Depth m','Area sqft','Shape','Frontage m','Discount %','Facing','Corner','Premium %','Price INR','Status','Row','Row frontage ft','Row depth ft','Row end'],...saleLots(c).map(p=>[c.id,p.id,p.use,p.w,p.h,p.area*SQFT,p.shape||'regular',p.frontage||p.w,p.discount||0,p.facing,p.corner?'Yes':'No',p.premium,plotValue(p,c.brief),status[p.id]||'Available',p.rowId||'',p.rowWidth?p.rowWidth/FT:'',p.rowDepth?p.rowDepth/FT:'',p.rowEnd?'Yes':'No'])]);}
export function financeCSV(concepts:Concept[]){return asCSV([['Concept','Plots','Regular plots','Irregular plots','Protected m2','Remaining m2','Land cost INR','Gross m2','Saleable %','Road m2','Park m2','Revenue INR','Infrastructure INR','Total cost INR','Profit INR','Margin %','Objective','Missing requested plots','Additional sizes','Arrangements tested','Park decision'],...concepts.map(c=>[c.id,saleLots(c).length,c.regularCount||0,c.irregularCount||0,c.protectedArea||0,c.unallocated,c.landTotal??c.brief.land,c.area,c.efficiency,c.roadsArea,c.parkArea,c.revenue,c.infra,c.cost,c.profit,c.margin,objectiveLabels[c.brief.objective||'area'],plotMixReport(c).shortfall,plotMixReport(c).extras.length,c.searchCount||0,c.parkDecision||''])]);}
export function cadDXF(c:Concept,zones:Exclusion[]){let body='0\nSECTION\n2\nHEADER\n9\n$INSUNITS\n70\n6\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n';
 const loop=(ps:{x:number;y:number}[],layer:string)=>{for(let i=0;i<ps.length;i++){const p=ps[i],q=ps[(i+1)%ps.length];body+=`0\nLINE\n8\n${layer}\n10\n${p.x}\n20\n${-p.y}\n11\n${q.x}\n21\n${-q.y}\n`;}};
 loop(c.boundary,'BOUNDARY');for(const p of c.lots){loop(lotPoints(p),p.use.toUpperCase());for(const hole of p.holes||[])loop(hole,`${p.use.toUpperCase()}_VOID`);}for(const z of zones)loop(corners(z),'EXCLUSIONS');
 if(c.roadPolygons){for(const p of c.roadPolygons)for(const [i,r] of p.entries())loop(r,i?'ROAD_VOID':'ROAD_SURFACE');}else for(const r of c.roads)for(const t of triangulate(c.boundary)){const p=clipToBox(t,r);if(p.length>=3)loop(p,'ROAD_SURFACE');}
 for(const f of c.access?.frontages||[]){const a=c.boundary[f.edge],z=c.boundary[(f.edge+1)%c.boundary.length];body+=`0\nLINE\n8\nEXISTING_ROAD_FRONTAGE\n10\n${a.x}\n20\n${-a.y}\n11\n${z.x}\n21\n${-z.y}\n`;}
 for(const r of c.access?.roads||[])for(let i=1;i<r.points.length;i++){const a=r.points[i-1],z=r.points[i];body+=`0\nLINE\n8\nEXISTING_ROAD_CENTERLINE\n10\n${a.x}\n20\n${-a.y}\n11\n${z.x}\n21\n${-z.y}\n`;}
 for(const [i,entry] of (c.entries||(c.access?.entrance?[c.entry]:[])).entries())body+=`0\nTEXT\n8\nENTRANCE\n10\n${entry.x}\n20\n${-entry.y}\n40\n2\n1\nENTRANCE ${i+1}\n`;
 for(const polygon of c.residualPolygons||[])for(const ring of polygon)loop(ring,'RESIDUAL_LAND');
 for(const p of saleLots(c))body+=`0\nTEXT\n8\nPLOT_NUMBERS\n10\n${p.x+1}\n20\n${-(p.y+p.h/2)}\n40\n1\n1\n${p.id}\n`;
 return body+'0\nENDSEC\n0\nEOF\n';
}
