'use client';
import NumberInput from './NumberInput';
import PlotMixControls from './PlotMixControls';
import {currency,landCost,polygonArea,SQFT,type Project,type Brief} from './planning';
import {CMDA_BASELINE,isTamilNadu} from './regulations';
export default function DevelopmentBrief({project,onChange,onGenerate,busy,onBack}:{project:Project;onChange:(p:Project)=>void;onGenerate:()=>void;busy:boolean;onBack:()=>void}){
 const b=project.brief,area=polygonArea(project.boundary),edit=(patch:Partial<Brief>)=>onChange({...project,brief:{...b,...patch}});
 const number=(label:string,key:keyof Brief,min:number,max:number,step=1)=><label className="ws-field">{label}<NumberInput min={min} max={max} step={step} value={b[key] as number} onCommit={value=>edit(key==='road'?{road:value,roadMax:Math.max(value,b.roadMax)}:key==='roadMax'?{roadMax:value,road:Math.min(value,b.road)}:{[key]:value})}/></label>;
 const recommend=()=>edit({park:'auto',objective:'area',allowExtraSizes:true,plotMix:[{width:30,depth:40,minCount:1,targetPercent:60},{width:30,depth:50,minCount:1,targetPercent:25},{width:40,depth:60,minCount:1,targetPercent:15}],road:9,roadMax:12,mixedRows:true,allowOdd:true,maxOddPercent:15,oddDiscount:10,parkPercent:10,clubhouseCount:area>=8000?1:0,clubhouseArea:1200,amenityArea:area>=8000?800:0,amenityType:'playground',amenityLocation:'beside-park'});
 return <section className="ws-brief-page"><div className="ws-page-heading"><div><span className="ws-eyebrow">YOUR DEVELOPMENT BRIEF</span><h1>Tell us what you want to build.</h1><p>{(area/4046.8564224).toFixed(2)} acres · We connect your entrances, prioritise regular plots and account for every part of the site.</p></div><button onClick={onBack}>Edit land & entrances</button></div>
 <div className="ws-brief-identity"><label className="ws-field">Project name<input value={b.name} onChange={e=>edit({name:e.target.value})}/></label><label className="ws-field">Location<input value={b.locality} placeholder="Village / city" onChange={e=>edit({locality:e.target.value})}/></label><label className="ws-field">Planning authority<select value={b.authority} onChange={e=>edit({authority:e.target.value as Brief['authority']})}><option>CMDA</option><option>DTCP</option><option>Karnataka LPA</option></select></label><button onClick={recommend}>Suggest starting requirements</button></div>
 <div className="ws-brief-grid"><article className="ws-card"><span className="ws-eyebrow">1 · PLOTS & ROADS</span><h2>What should sell here?</h2><PlotMixControls brief={b} onChange={edit}/><div className="ws-inline-fields">{number('Minimum road (m)','road',6,24,.1)}{number('Maximum road (m)','roadMax',6,24,.1)}</div><label className="ws-toggle"><span>Roads must extend to neighbouring land<small>Apply the 9 m extendable-road baseline; confirm with your consultant.</small></span><input type="checkbox" checked={!!b.extendableRoads} onChange={e=>edit({extendableRoads:e.target.checked})}/></label><label className="ws-field">Road layout<select value={b.roadStyle} onChange={e=>edit({roadStyle:e.target.value as Brief["roadStyle"]})}><option value="straight">Straight streets</option><option value="auto">Compare straight streets and roundabout</option><option value="roundabout">Include a roundabout</option></select></label>{b.roadStyle!=="straight"&&number("Roundabout outer diameter (m)","roundaboutDiameter",22,60)}<p className="ws-helper">The optimizer compares saleable area and design checks. A roundabout uses real road and island area; turning paths still need engineering review.</p><p className="ws-helper">Main and secondary roads can use different widths within this range. Length-based rule checks limit how narrow each can be. Set the same minimum and maximum for uniform roads.</p><label className="ws-toggle"><span>Allow useful irregular edge plots<small>Regular plots remain the priority.</small></span><input type="checkbox" checked={b.allowOdd} onChange={e=>edit({allowOdd:e.target.checked})}/></label>{b.allowOdd&&<div className="ws-inline-fields">{number('Maximum irregular plots (%)','maxOddPercent',0,30)}{number('Irregular price discount (%)','oddDiscount',0,50)}</div>}<label className="ws-toggle"><span>Include commercial sites<small>Use and location need authority review.</small></span><input type="checkbox" checked={b.commercial} onChange={e=>edit({commercial:e.target.checked})}/></label></article>
 <article className="ws-card"><span className="ws-eyebrow">2 · PARK & AMENITIES</span><h2>Make room for daily life.</h2><p>A connected park, with separately sized facilities beside it.</p>{number('Park target (% of gross land)','parkPercent',0,25,.5)}<label className="ws-field">Preferred park location<select value={b.park} onChange={e=>edit({park:e.target.value as Brief['park']})}><option value="auto">Automatic · compare space and access</option><option value="central">Prefer central</option><option value="north">Upper part of drawing</option><option value="south">Lower part of drawing</option></select></label><div className="ws-inline-fields">{number('Number of clubhouses','clubhouseCount',0,5)}{number('Each clubhouse (sq ft)','clubhouseArea',100,50000,100)}</div><label className="ws-field">Additional amenity<select value={b.amenityType} onChange={e=>edit({amenityType:e.target.value as Brief['amenityType']})}><option value="playground">Playground</option><option value="sports">Sports court</option><option value="parking">Visitor parking</option></select></label>{number('Amenity area (sq ft; 0 = none)','amenityArea',0,100000,100)}<label className="ws-field">Place amenity<select value={b.amenityLocation} onChange={e=>edit({amenityLocation:e.target.value as Brief['amenityLocation']})}><option value="beside-park">Beside the park</option><option value="near-entrance">Near an entrance</option></select></label><p className="ws-helper">Clubhouses and private amenities do not consume or count towards the OSR reserve. If they do not fit, the plan reports the shortfall.</p></article>
 <article className="ws-card"><span className="ws-eyebrow">3 · COST & SELLING PRICE</span><h2>Set your business targets.</h2><label className="ws-field">Land purchase price basis<select value={b.landBasis} onChange={e=>{const basis=e.target.value as Brief['landBasis'],total=landCost(b,area),factor=basis==='acre'?area/4046.8564224:basis==='sqft'?area*SQFT:1;edit({landBasis:basis,land:Math.round(total/factor)});}}><option value="total">Total land cost</option><option value="acre">Price per acre</option><option value="sqft">Price per sq ft</option></select></label>{number(b.landBasis==='total'?'Total land cost (₹)':b.landBasis==='acre'?'Land price (₹ / acre)':'Land price (₹ / sq ft)','land',0,1e12)}<div className="ws-area-total"><span>Total land purchase</span><b>{currency(landCost(b,area))}</b></div>{number('Expected selling price (₹ / sq ft)','price',0,1e7)}{number('Target profit margin (%)','targetMargin',0,90)}<details className="ws-details"><summary>Development cost assumptions</summary>{number('Road construction (₹ / m²)','roadRate',0,1e7,100)}{number('Approvals & consultants (₹)','fees',0,1e10)}{number('Marketing (% of revenue)','marketing',0,30,.5)}</details><p className="ws-helper">Profit is calculated after land, infrastructure, consultants and marketing. Financing and tax are not included. The target is your threshold, not a promised return.</p></article></div>
 <details className="ws-details ws-brief-advanced"><summary>Protected land, EWS and advanced requirements</summary>{number('Preferred EWS area share (%)','ewsPercent',0,30)}<p className="ws-helper">The sourced baseline may require a higher EWS land allocation. Dimensions and use restrictions still need review.</p><button onClick={()=>onChange({...project,exclusions:[...project.exclusions,{id:String(Date.now()),x:5,y:5,w:10,h:10,label:'Protected area',type:'no-build'}]})}>Add no-build / water / existing structure</button>{project.exclusions.map(z=><div className="ws-zone" key={z.id}><input aria-label="Constraint label" value={z.label} onChange={e=>onChange({...project,exclusions:project.exclusions.map(q=>q.id===z.id?{...q,label:e.target.value}:q)})}/><select aria-label="Constraint type" value={z.type} onChange={e=>onChange({...project,exclusions:project.exclusions.map(q=>q.id===z.id?{...q,type:e.target.value as typeof z.type}:q)})}><option value="no-build">No-build / easement</option><option value="water">Water body</option><option value="structure">Existing structure</option></select><div className="ws-inline-fields">{(['x','y','w','h'] as const).map(key=><label className="ws-field" key={key}>{key} (metres)<input type="number" value={z[key]} min={key==='w'||key==='h'?1:0} onChange={e=>onChange({...project,exclusions:project.exclusions.map(q=>q.id===z.id?{...q,[key]:Math.max(key==='w'||key==='h'?1:0,Number(e.target.value))}:q)})}/></label>)}</div><button onClick={()=>onChange({...project,exclusions:project.exclusions.filter(q=>q.id!==z.id)})}>Remove constraint</button></div>)}</details>
 {isTamilNadu(b.authority)&&<div className="ws-rule-note"><b>{CMDA_BASELINE.title}</b><p>{CMDA_BASELINE.caveat}</p><a href={CMDA_BASELINE.source} target="_blank" rel="noreferrer">Original Rule 47</a> · <a href={CMDA_BASELINE.amendment} target="_blank" rel="noreferrer">2020 amendment</a></div>}
 <div className="ws-brief-footer"><div><b>Ready to explore the trade-offs?</b><p>Compare regular plots, edge plots, remaining land and profit in five concepts.</p></div><button className="ws-primary" disabled={busy} onClick={onGenerate}>{busy?'Planning layouts…':'Generate layout options'}</button></div>
 </section>;
}
