'use client';
import {useRef,useState} from 'react';
import type {CropBox,SurveyImage} from './survey';
import {lotPoints,siteEntrances,triangulate,polygonArea,extent,saleLots,SQFT,type Concept,type Exclusion,type Lot,type XY} from './planning';
export type Layers={dimensions:boolean;numbers:boolean;landscape:boolean;roads:boolean;constraints:boolean};
const colors:Record<string,string>={residential:'#f7f2e6',ews:'#e6eef8',commercial:'#ebd7bd',park:'#d5e6c9',utility:'#d9d5ec',clubhouse:'#d8c9b1',amenity:'#c3dbdc',infrastructure:'#bec9d0'};
function roadAt(c:Concept,p:XY){
 const inside=(ring:XY[])=>{let yes=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a.y>p.y)!==(b.y>p.y)&&p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x)yes=!yes;}return yes;};
 return !c.roadPolygons||c.roadPolygons.some(rings=>inside(rings[0])&&!rings.slice(1).some(inside));
}
function labelPoint(p:Lot){if(!p.polygon)return{x:p.x+p.w/2,y:p.y+p.h/2};const triangle=triangulate(p.polygon).sort((a,b)=>polygonArea(b)-polygonArea(a))[0];return triangle?{x:triangle.reduce((s,q)=>s+q.x,0)/3,y:triangle.reduce((s,q)=>s+q.y,0)/3}:{x:p.x+p.w/2,y:p.y+p.h/2};}
export function PlanDrawing({concept:c,exclusions=[],selected,onSelect,onResidualSelect,selectedResidual,layers={dimensions:false,numbers:true,landscape:true,roads:true,constraints:true},id='plan',technical=false,showAccess=false}:{concept:Concept;exclusions?:Exclusion[];selected?:string;onSelect?:(p:Lot)=>void;onResidualSelect?:(index:number)=>void;selectedResidual?:number|null;layers?:Layers;id?:string;technical?:boolean;showAccess?:boolean}){
 const b=extent(c.boundary),parks=c.lots.filter(p=>p.use==='park');
 const pt=(p:XY[])=>p.map(q=>`${q.x},${q.y}`).join(' ');
 return <>
 <defs><pattern id={`${id}-grid`} width="10" height="10" patternUnits="userSpaceOnUse"><path d="M10 0H0V10" fill="none" stroke="#d9ded6" strokeWidth=".13"/></pattern><clipPath id={`${id}-boundary`}><polygon points={pt(c.boundary)}/></clipPath><pattern id={`${id}-hatch`} width="3" height="3" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><line x1="0" y1="0" x2="0" y2="3" stroke="#b57464" strokeWidth=".45"/></pattern></defs>
 <rect x="-40" y="-40" width={b.w+80} height={b.h+90} fill={technical?'#fff':'#f0f1ec'}/><rect x="-40" y="-40" width={b.w+80} height={b.h+90} fill={`url(#${id}-grid)`}/>
 <g clipPath={`url(#${id}-boundary)`}><polygon points={pt(c.boundary)} fill={technical?'white':'#e1e5d9'}/>
 {c.residualPolygons?.map((polygon,i)=><path key={`residual-${i}`} d={polygon.map(r=>`M${r.map(p=>`${p.x},${p.y}`).join('L')}Z`).join('')} role={onResidualSelect?"button":undefined} tabIndex={onResidualSelect?0:undefined} aria-label={`Unallocated area ${i+1}`} onClick={()=>onResidualSelect?.(i)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onResidualSelect?.(i);}}} style={{cursor:onResidualSelect?"pointer":undefined}} fill={selectedResidual===i?"#bdab7c":"#d8dacf"} fillRule="evenodd" stroke="#b6bbab" strokeWidth=".18" strokeDasharray="1 1"/>)}
 {layers.roads&&(c.roadPolygons?c.roadPolygons.map((p,i)=><path key={i} d={p.map(r=>`M${r.map(q=>`${q.x},${q.y}`).join("L")}Z`).join("")} fillRule="evenodd" fill={showAccess?"#f0b7a5":technical?"#fff":"#fafaf6"}/>):c.roads.map((r,i)=><rect key={i} x={r.x} y={r.y} width={r.w} height={r.h} fill={technical?'#fff':'#fafaf6'}/>))}
 {showAccess&&c.reachableRoadPolygons?.map((p,i)=><path key={`reachable-${i}`} d={p.map(r=>`M${r.map(q=>`${q.x},${q.y}`).join('L')}Z`).join('')} fill="#9dd6c4" fillRule="evenodd" pointerEvents="none"/>)}
 {c.lots.map(p=>{const sale=['residential','ews','commercial'].includes(p.use),sel=selected===p.id&&sale,center=labelPoint(p);return <g key={p.id} role={sale&&onSelect?'button':undefined} tabIndex={sale&&onSelect?0:undefined} aria-label={sale?`Plot ${p.id}, ${Math.round(p.area*SQFT)} square feet, ${p.facing} facing`:p.use} onClick={e=>{e.stopPropagation();if(sale)onSelect?.(p);}} onKeyDown={e=>{if(sale&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onSelect?.(p);}}} className={sale?'ws-lot':''}>
  <path d={[lotPoints(p),...(p.holes||[])].map(r=>`M${r.map(q=>`${q.x},${q.y}`).join("L")}Z`).join("")} fillRule="evenodd" fill={sel?'#405e51':technical?'white':colors[p.use]} stroke={sel?'#244634':p.locked?'#435d84':'#7f8b79'} strokeWidth={sel?.65:.23}/>
  {p.use==='park'&&layers.landscape&&<><defs><clipPath id={`${id}-${p.id}-park`}><polygon points={lotPoints(p).map(q=>`${q.x},${q.y}`).join(' ')}/></clipPath></defs><g clipPath={`url(#${id}-${p.id}-park)`}>
   {p.w>20&&<rect x={p.x+3} y={p.y+3} width={Math.max(1,p.w-6)} height={Math.max(1,p.h-6)} rx="3" fill="none" stroke="#eef4df" strokeWidth="1.2"/>}
   {Array.from({length:Math.max(2,Math.floor(p.w/8))},(_,i)=>i).map(i=>[.23,.78].map((v,j)=><g key={`${i}-${j}`}><circle cx={p.x+4+i*(p.w-8)/Math.max(1,Math.floor(p.w/8)-1)} cy={p.y+p.h*v} r={Math.min(2.2,p.w*.17)} fill="#abc68f" stroke="#83a869" strokeWidth=".15"/><circle cx={p.x+4+i*(p.w-8)/Math.max(1,Math.floor(p.w/8)-1)-.35} cy={p.y+p.h*v-.25} r={Math.min(1.45,p.w*.11)} fill="#bcd5a4"/></g>))}
  </g></>}

  {sale&&layers.numbers&&<><text x={center.x} y={center.y-.5} textAnchor="middle" fill={sel?'#fff':'#465140'} fontSize="2.45" fontWeight="500">{p.id}</text><text x={center.x} y={center.y+2.4} textAnchor="middle" fill={sel?'#d5e5d5':'#839077'} fontSize="1.65">{Math.round(p.area*SQFT)} sf</text></>}
  {!sale&&p.use!=='park'&&<text x={p.x+p.w/2} y={p.y+p.h/2} textAnchor="middle" fontSize="1.8" fill="#6b685d">{p.label||(p.use==='utility'?'PUBLIC USE':p.use==='amenity'?'AMENITY':'CLUBHOUSE')}</text>}
  {p.locked&&<text x={p.x+1} y={p.y+2.5} fontSize="1.7" fill="#3f6287">L</text>}
  {layers.dimensions&&sale&&p.shape!=='irregular'&&<><text x={p.x+p.w/2} y={p.y+1.8} textAnchor="middle" fontSize="1.45" fill={sel?'#e2eadf':'#7a8271'}>{p.w.toFixed(2)}</text><text x={p.x+1.5} y={p.y+p.h/2} textAnchor="middle" fontSize="1.45" fill={sel?'#e2eadf':'#7a8271'} transform={`rotate(-90 ${p.x+1.5} ${p.y+p.h/2})`}>{p.h.toFixed(2)}</text></>}
 </g>;})}
 {layers.constraints&&exclusions.map(z=><g key={z.id}><rect x={z.x} y={z.y} width={z.w} height={z.h} fill={z.type==='water'?'#c3dce3':`url(#${id}-hatch)`} stroke="#ac7668" strokeDasharray="1 1" strokeWidth=".4"/><text x={z.x+z.w/2} y={z.y+z.h/2} textAnchor="middle" fontSize="2">{z.label}</text></g>)}
 </g>
 <polygon points={pt(c.boundary)} fill="none" stroke="#3e4c39" strokeWidth=".65"/>
 {c.boundary.map((p,i)=>{const q=c.boundary[(i+1)%c.boundary.length],d=Math.hypot(p.x-q.x,p.y-q.y),angle=Math.atan2(q.y-p.y,q.x-p.x)*180/Math.PI;return <g key={i}><circle cx={p.x} cy={p.y} r=".85" fill="#fff" stroke="#40513c" strokeWidth=".3"/>{layers.dimensions&&<text x={(p.x+q.x)/2} y={(p.y+q.y)/2-2} transform={`rotate(${angle>90||angle< -90?angle+180:angle} ${(p.x+q.x)/2} ${(p.y+q.y)/2})`} fontSize="2.1" textAnchor="middle" fill="#66745d">{d.toFixed(2)} m</text>}</g>;})}
 {layers.roads&&<><line x1={c.spine} y1="0" x2={c.spine} y2={b.h} stroke="#a5afa0" strokeDasharray="2 2.5" strokeWidth=".2" clipPath={`url(#${id}-boundary)`}/><text x={c.spine+1.1} y={b.h*.7} fontSize="2.1" fill="#909886" transform={`rotate(-90 ${c.spine+1.1} ${b.h*.7})`}>{c.brief.road.toFixed(1)} M MAIN STREET</text>{c.roads.filter(r=>roadAt(c,{x:r.x+r.w*.68,y:r.y+r.h/2})&&r.w>c.brief.road*1.5&&r.h>=Math.min(c.brief.road,c.secondaryRoadWidth??c.brief.road)-.01).map((r,i)=><text key={i} x={r.x+r.w*.68} y={r.y+r.h/2+.7} textAnchor="middle" fontSize="2" fill="#8b9580">{Math.min(r.w,r.h).toFixed(1)} M ROAD</text>)}</>}
 {parks.map(p=>{const center=labelPoint(p);return <g key={`label-${p.id}`}><rect x={center.x-14} y={center.y-3} width="28" height="8" rx="1" fill="#f3f8ed" opacity=".95"/><text x={center.x} y={center.y} textAnchor="middle" fontSize="2.8" fill="#416737">PARK / OSR</text><text x={center.x} y={center.y+3} textAnchor="middle" fontSize="2" fill="#729465">{Math.round(p.area).toLocaleString()} m²</text></g>;})}
 <g transform={`translate(${b.w+13} 5)`}>{c.access?.northAngle!=null?<><g transform={`rotate(${c.access.northAngle} 3 5)`}><path d="M0 10L3 0L6 10L3 7Z" fill="#334631"/></g><text x="3" y="-3" textAnchor="middle" fontSize="3">N</text></>:<text x="0" y="0" fontSize="2.3" fill="#7f8d74">North unknown</text>}</g>
 {c.access?.frontages.map(f=>{const a=c.boundary[f.edge],z=c.boundary[(f.edge+1)%c.boundary.length];return <line key={f.edge} x1={a.x} y1={a.y} x2={z.x} y2={z.y} stroke="#367b9a" strokeWidth="1.4"/>;})}
 {(c.entries|| (c.access?.entrance?[c.entry]:[])).map((entry,i)=><g key={`entry-${i}`}>{(()=>{const e=siteEntrances(c.access)[i];if(!e)return null;const a=c.boundary[e.edge],z=c.boundary[(e.edge+1)%c.boundary.length],length=Math.hypot(z.x-a.x,z.y-a.y),half=(e.entranceWidth??9)/2;return <line x1={entry.x-(z.x-a.x)/length*half} y1={entry.y-(z.y-a.y)/length*half} x2={entry.x+(z.x-a.x)/length*half} y2={entry.y+(z.y-a.y)/length*half} stroke="#b88a4f" strokeWidth="2"/>;})()}<circle cx={entry.x} cy={entry.y} r="2.5" fill="#b88a4f"/><text x={entry.x} y={entry.y-4} textAnchor="middle" fontSize="2.8">ENTRANCE {i+1} · {siteEntrances(c.access)[i]?.entranceWidth??9} M</text></g>)}
 <g transform={`translate(0 ${b.h+27})`}><path d="M0 0h20m-20-1v2m10-2v2m10-2v2" stroke="#57684d" strokeWidth=".4"/><text x="0" y="4" fontSize="1.8">0</text><text x="18" y="4" fontSize="1.8">20 m</text><text x={b.w} y="3" textAnchor="end" fontSize="2" fill="#929989">CONCEPT {c.id} · ALL DIMENSIONS IN METRES</text></g>
 </>;
}
export function MiniPlan({concept}:{concept:Concept}){const b=extent(concept.boundary);return <svg aria-label={`Concept ${concept.id}, ${saleLots(concept).length} plots`} viewBox={`-8 -8 ${b.w+16} ${b.h+16}`}><polygon points={concept.boundary.map(p=>`${p.x},${p.y}`).join(' ')} fill="#e7eade"/>{concept.lots.map(p=><path key={p.id} d={[lotPoints(p),...(p.holes||[])].map(r=>`M${r.map(q=>`${q.x},${q.y}`).join("L")}Z`).join("")} fillRule="evenodd" fill={colors[p.use]} stroke="#a6b39a" strokeWidth=".35"/>)}</svg>;}
export default function PlanCanvas({concept,exclusions,selected,onSelect,onResidualSelect,selectedResidual,layers,technical,onDraw,draw=false,survey,points,onPointsChange,canConfirm,areaLabel,cropping=false,onCrop,onCancelCrop}:{concept:Concept;exclusions:Exclusion[];selected:string;onSelect:(p:Lot)=>void;onResidualSelect?:(index:number)=>void;selectedResidual?:number|null;layers:Layers;technical:boolean;onDraw?:(p:XY[])=>void;draw?:boolean;survey?:SurveyImage|null;points:XY[];onPointsChange:(p:XY[])=>void;canConfirm:boolean;areaLabel:string;cropping?:boolean;onCrop?:(c:CropBox)=>void;onCancelCrop?:()=>void}){
 const b=draw&&survey?{w:200,h:200*survey.height/survey.width}:concept.boundary.length?extent(concept.boundary):{w:200,h:140};
 const svg=useRef<SVGSVGElement>(null),[zoom,setZoom]=useState(1),[pan,setPan]=useState(false),[offset,setOffset]=useState({x:0,y:0}),[active,setActive]=useState<number|null>(null);
 const [cropPoints,setCropPoints]=useState<XY[]>([]),[showAccess,setShowAccess]=useState(false);
 const moving=useRef<number|null>(null),drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
 const width=b.w+40,height=b.h+(draw?30:48),cx=b.w/2+offset.x,cy=b.h/2+(draw?0:8)+offset.y;
 function position(e:React.PointerEvent){const m=svg.current?.getScreenCTM()?.inverse();if(!m)return{x:0,y:0};const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m);return{x:Math.round(p.x*100)/100,y:Math.round(p.y*100)/100};}
 function removePoint(index:number){onPointsChange(points.filter((_,i)=>i!==index));setActive(null);}
 return <div className="ws-canvas"><div className="ws-canvas-info"><span className="ws-live-dot"/> {draw?'Map your land':technical?'Technical drawing':'Development masterplan'} <b>{draw?areaLabel:concept.id?`Concept ${concept.id}`:''}</b></div>
 {showAccess&&!draw&&<div className="ws-exit-key"><span><i style={{background:'#9dd6c4'}}/>Entrance-connected street</span><span><i style={{background:'#f0b7a5'}}/>Width / access not verified</span></div>}
 <svg ref={svg} style={{touchAction:'none'}} className={draw?'is-drawing':''} aria-label="Interactive development masterplan" viewBox={`${cx-width/(2*zoom)} ${cy-height/(2*zoom)} ${width/zoom} ${height/zoom}`} onPointerDown={e=>{if(cropping&&!pan){setCropPoints(v=>v.length>=2?[position(e)]:[...v,position(e)]);return;}if(draw&&!pan){onPointsChange([...points,position(e)]);setActive(points.length);return;}if(pan||e.target===e.currentTarget||(e.target as Element).tagName==='rect'){drag.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};e.currentTarget.setPointerCapture(e.pointerId);}}} onPointerMove={e=>{if(moving.current!==null){const i=moving.current;onPointsChange(points.map((p,j)=>i===j?position(e):p));return;}if(!drag.current||!svg.current)return;const scale=svg.current.getScreenCTM()?.a||1;setOffset({x:drag.current.ox-(e.clientX-drag.current.x)/scale,y:drag.current.oy-(e.clientY-drag.current.y)/scale});}} onPointerUp={()=>{drag.current=null;moving.current=null;}} onPointerCancel={()=>{drag.current=null;moving.current=null;}}>
 {draw?survey?<image href={survey.url} x="0" y="0" width={b.w} height={b.h}/>:<rect x="-20" y="-20" width={b.w+40} height={b.h+40} fill="#f3f5ef"/>:concept.boundary.length?<PlanDrawing concept={concept} exclusions={exclusions} selected={selected} onSelect={onSelect} onResidualSelect={onResidualSelect} selectedResidual={selectedResidual} layers={layers} technical={technical} showAccess={showAccess}/>:null}
 {draw&&!cropping&&<g><polygon points={points.map(p=>`${p.x},${p.y}`).join(' ')} stroke="#426c53" strokeWidth={.6/zoom} fill="#699f6428" pointerEvents="none"/>
 {points.length>=3&&points.map((p,i)=>{const q=points[(i+1)%points.length],x=(p.x+q.x)/2,y=(p.y+q.y)/2;return <g key={`mid-${i}`} role="button" tabIndex={0} aria-label={`Add corner after ${i+1}`} onPointerDown={e=>{e.stopPropagation();if(pan)return;onPointsChange([...points.slice(0,i+1),{x,y},...points.slice(i+1)]);setActive(i+1);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onPointsChange([...points.slice(0,i+1),{x,y},...points.slice(i+1)]);}}}><circle cx={x} cy={y} r={2.2/zoom} fill="white" stroke="#426c53" strokeWidth={.4/zoom}/><text x={x} y={y+1/zoom} textAnchor="middle" fontSize={3.4/zoom} fill="#426c53" pointerEvents="none">+</text></g>;})}
 {points.map((p,i)=><g key={i} role="button" tabIndex={0} aria-label={`Boundary corner ${i+1}`} onPointerDown={e=>{e.stopPropagation();if(pan)return;setActive(i);moving.current=i;svg.current?.setPointerCapture(e.pointerId);}} onKeyDown={e=>{if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();removePoint(i);}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const delta=e.shiftKey?1:.1;onPointsChange(points.map((q,j)=>i===j?{x:q.x+(e.key==='ArrowRight'?delta:e.key==='ArrowLeft'?-delta:0),y:q.y+(e.key==='ArrowDown'?delta:e.key==='ArrowUp'?-delta:0)}:q));}}}><circle cx={p.x} cy={p.y} r={3/zoom} fill={active===i?'#d3a45f':'#426c53'} stroke="white" strokeWidth={.6/zoom}/><text x={p.x} y={p.y+1/zoom} textAnchor="middle" fill="white" fontSize={2.8/zoom} pointerEvents="none">{i+1}</text></g>)}
 </g>}
 {cropping&&cropPoints.length===2&&<rect x={Math.min(cropPoints[0].x,cropPoints[1].x)} y={Math.min(cropPoints[0].y,cropPoints[1].y)} width={Math.abs(cropPoints[1].x-cropPoints[0].x)} height={Math.abs(cropPoints[1].y-cropPoints[0].y)} fill="#548fb333" stroke="#367b9a" strokeWidth=".7" pointerEvents="none"/>}
 </svg>
 <div className="ws-canvas-tools">{!draw&&<button aria-pressed={showAccess} onClick={()=>setShowAccess(v=>!v)}>{showAccess?"Hide exit access":"Show exit access"}</button>}<button aria-pressed={pan} onClick={()=>setPan(v=>!v)} className={pan?'active':''}>{pan?'Move drawing':'Move / pan'}</button><button aria-label="Zoom out" onClick={()=>setZoom(v=>Math.max(.5,v-.5))}>−</button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>setZoom(v=>Math.min(12,v+.5))}>+</button><button onClick={()=>{setZoom(1);setOffset({x:0,y:0});}}>Fit</button></div>
 {cropping?<div className="ws-draw-help"><span>Click the top-left and bottom-right of the parcel area. Leave title blocks and notes outside.</span><button onClick={()=>{setCropPoints([]);onCancelCrop?.();}}>Cancel crop</button><button disabled={cropPoints.length!==2} onClick={()=>{const [a,z]=cropPoints,x=Math.max(0,Math.min(a.x,z.x)/b.w),y=Math.max(0,Math.min(a.y,z.y)/b.h),w=Math.min(1-x,Math.abs(a.x-z.x)/b.w),h=Math.min(1-y,Math.abs(a.y-z.y)/b.h);if(w>.02&&h>.02){onCrop?.({x,y,w,h});setCropPoints([]);}}}>Find boundary in this area</button></div>:draw?<div className="ws-draw-help"><span>{pan?'Drag to move the drawing. Turn off Move / pan to edit corners.':!canConfirm?'Enter your total land area in the site settings.':'Click outside corners. Drag dots to adjust; + adds a corner.'}</span><button disabled={!points.length} onClick={()=>{onPointsChange(points.slice(0,-1));setActive(null);}}>Undo point</button><button disabled={active===null||!points[active]} onClick={()=>active!==null&&removePoint(active)}>Delete selected</button><button onClick={()=>{onPointsChange([]);setActive(null);}}>Start outline again</button><button className="ws-primary" disabled={points.length<3||!canConfirm} onClick={()=>onDraw?.(points)}>Confirm boundary{areaLabel?` · ${areaLabel}`:''}</button></div>:<div className="ws-canvas-caption">{showAccess?"Green: verified full-width route to an entrance · Peach: road surface without a verified full-width route":"Click grey land to assign a use · Click plots to inspect · Drag to pan · Dimensions in metres"}</div>}
 {!draw&&concept.boundary.length>0&&<div className="ws-legend">{[['Residential','residential'],['EWS','ews'],['Commercial','commercial'],['Park / OSR','park'],['Public use','utility'],['Amenities','amenity']].map(([label,use])=><span key={use}><i style={{background:colors[use]}}/>{label}</span>)}</div>}
 </div>;
}
