'use client';
import {useState} from 'react';
import NumberInput from './NumberInput';
import {PLOT_TEMPLATES,selectedPlotSizes,objectiveLabels,type Brief,type PlotSize} from './planning';
export default function PlotMixControls({brief:b,onChange:edit}:{brief:Brief;onChange:(patch:Partial<Brief>)=>void}){
 const sizes=selectedPlotSizes(b),[width,setWidth]=useState(30),[depth,setDepth]=useState(40);
 const update=(plotMix:PlotSize[])=>{if(!plotMix.length)return;edit({plotMix,mixedRows:true,frontage:plotMix[0].width,depth:plotMix[0].depth,...(plotMix.some(s=>s.width*s.depth<775)?{affordablePlots:true}:{})});};
 const toggle=(w:number,d:number)=>{const selected=sizes.some(s=>s.width===w&&s.depth===d);update(selected?sizes.filter(s=>s.width!==w||s.depth!==d):[...sizes,{width:w,depth:d,minCount:1,targetPercent:0}]);};
 return <div className="ws-mix-controls"><p className="ws-helper">Select the sizes you want to sell. One standard size repeats along each row; extra sizes need your permission.</p><div className="ws-size-options" role="group" aria-label="Choose plot sizes">{PLOT_TEMPLATES.map(([w,d])=>{const active=sizes.some(s=>s.width===w&&s.depth===d);return <button type="button" aria-pressed={active} disabled={(active&&sizes.length===1)||(!active&&sizes.length>=12)} className={active?'active':''} key={`${w}x${d}`} onClick={()=>toggle(w,d)}>{active?'✓ ':''}{w} × {d}<small>{w*d} sq ft{w*d===600?' · EWS':''}</small></button>;})}</div>
 <details className="ws-details"><summary>Counts, target shares & custom sizes</summary><p className="ws-helper">Minimum counts are requirements. Share is a preferred percentage of residential + EWS plot count; 0 means no share target. Total targets cannot exceed 100%.</p>{sizes.map((size,i)=><div className="ws-mix-row" key={`${size.width}x${size.depth}`}><b>{size.width} × {size.depth} ft</b><div className="ws-inline-fields"><label className="ws-field">Minimum count<NumberInput value={size.minCount} min={0} max={2000} step={1} onCommit={value=>update(sizes.map((s,j)=>j===i?{...s,minCount:Math.round(value)}:s))}/></label><label className="ws-field">Target share (%)<NumberInput value={size.targetPercent} min={0} max={Math.max(0,100-sizes.reduce((n,s,j)=>n+(i===j?0:s.targetPercent),0))} step={1} onCommit={value=>update(sizes.map((s,j)=>j===i?{...s,targetPercent:value}:s))}/></label></div><button type="button" disabled={sizes.length===1} onClick={()=>update(sizes.filter((_,j)=>i!==j))}>Remove size</button></div>)}<div className="ws-inline-fields"><label className="ws-field">Custom width (ft)<NumberInput value={width} min={20} max={60} onCommit={setWidth}/></label><label className="ws-field">Custom depth (ft)<NumberInput value={depth} min={30} max={80} onCommit={setDepth}/></label></div><button type="button" disabled={sizes.length>=12||sizes.some(s=>s.width===width&&s.depth===depth)} onClick={()=>toggle(width,depth)}>Add custom size</button></details>
 <label className="ws-toggle"><span>Allow additional sizes to improve the layout<small>Includes adjusted row ends and, when enabled, irregular plots. All deviations appear in the result.</small></span><input type="checkbox" checked={b.allowExtraSizes!==false} onChange={e=>edit({allowExtraSizes:e.target.checked,plotMix:sizes})}/></label>{b.allowExtraSizes===false&&<p className="ws-helper">Strict sizes: newly generated residential plots must match the selected dimensions. More land may remain unallocated. Existing locked plots are retained and reported.</p>}
 <label className="ws-field">What should the planner optimize?<select value={b.objective||'area'} onChange={e=>edit({objective:e.target.value as Brief['objective'],plotMix:sizes})}>{Object.entries(objectiveLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><p className="ws-helper">Access, design checks and minimum counts come first. Profit uses your selling price and development costs; share targets guide the mix objective.</p>{b.objective==='profit'&&b.price<=0&&<p className="ws-rule-note">Enter your expected selling price in the development brief before comparing profit.</p>}
 </div>;
}
