'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import NumberInput from './NumberInput';
import {useLayoutCalculation,repriceConcept,planningJob} from './planning-client';
import DevelopmentBrief from './DevelopmentBrief';
import PlotMixControls from './PlotMixControls';
import ConceptExplanation from './ConceptExplanation';
import {CMDA_BASELINE} from './regulations';
import AccessCanvas from './AccessCanvas';
import type {BoundarySuggestion} from './boundary-detection';
import PlanCanvas, { MiniPlan, PlanDrawing, type Layers } from './PlanCanvas';
import { applyInstruction, allocationEligibility, residualArea, type AreaAllocation, plotMixReport, rowSchedule, siteEntrances, plotValue, landCost, boundaryFromArea, emptyAccess, type TargetSolution, currency, extent, blankProject, emptyConcept, parseCoordinates, parseProject, polygonArea, saleLots, SQFT, validateBoundary, type Brief, type Lot, type Project } from './planning';
import { cadDXF, financeCSV, inventoryCSV, saveFile } from './deliverables';
import { readSurvey, suggestBoundaries, type CropBox, type SurveyImage } from './survey';
import './studio.css';

const steps = ['Your site', 'Development brief', 'Layout options', 'Business case', 'Team handoff'];
const departments = ['Planning', 'Architect', 'Finance', 'Management', 'Sales', 'Marketing', 'Approval consultant'];
const defaultLayers: Layers = { dimensions: false, numbers: true, landscape: true, roads: true, constraints: true };
const paths: Record<string, string> = {
  grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',
  upload:'M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5',
  arrow:'M5 12h14m-6-6 6 6-6 6',
  settings:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6',
  layers:'m12 3 10 5-10 5L2 8Zm-9 10 9 5 9-5m-18 5 9 5 9-5',
  wand:'m4 20 12-12 4 4-12 12M14 3v3m5-4v3m3 3h-3M2 10h4M4 8v4',
  download:'M12 3v13m-5-5 5 5 5-5M4 17v4h16v-4',
  check:'m4 12 5 5L20 6',
  close:'m6 6 12 12M18 6 6 18',
  lock:'M6 10h12v11H6zM8 10V6a4 4 0 0 1 8 0v4',
  compare:'M3 4h7v16H3zM14 4h7v16h-7z',
  file:'M5 2h9l5 5v15H5zM14 2v6h5M8 12h8M8 16h8',
  undo:'M7 3 2 8l5 5M2 8h11a7 7 0 0 1 0 14',
};
function Icon({name,size=17}:{name:string;size?:number}) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.grid}/></svg>; }
function Badge({state,children}:{state:string;children:React.ReactNode}) { return <span className={`ws-badge ${state}`}>{children}</span>; }
function Metric({label,value,note}:{label:string;value:string;note?:string}) { return <div className="ws-metric"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>; }

export default function Studio() {
  const [project,setProject]=useState<Project>(blankProject);
  const [step,setStep]=useState(0),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [selectedResidual,setSelectedResidual]=useState<{key:string;conceptId:string;index:number}|null>(null);
  const [selectedPlot,setSelectedPlot]=useState(''),[layers,setLayers]=useState(defaultLayers),[technical,setTechnical]=useState(false);
  const focusBeforeModal=useRef<HTMLElement|null>(null);
  const [compare,setCompare]=useState(false),[sourceOpen,setSourceOpen]=useState(false),[help,setHelp]=useState(false),[sidebar,setSidebar]=useState(false);
  const [reportTab,setReportTab]=useState('Financials'),[handoffTab,setHandoffTab]=useState('Deliverables'),[department,setDepartment]=useState('Planning');
  const [command,setCommand]=useState(''),[messages,setMessages]=useState<string[]>([]),[previous,setPrevious]=useState<Project|null>(null);
  const [survey,setSurvey]=useState<SurveyImage|null>(null),[surveyFile,setSurveyFile]=useState<File|null>(null),[pageNumber,setPageNumber]=useState(1);
  const [drawing,setDrawing]=useState(false),[landArea,setLandArea]=useState(''),[areaUnit,setAreaUnit]=useState<'sqft'|'acres'|'sqm'>('acres');
  const [suggestions,setSuggestions]=useState<BoundarySuggestion[]>([]),[detecting,setDetecting]=useState(false),[cropping,setCropping]=useState(false),[accessMode,setAccessMode]=useState(false),[uploadKind,setUploadKind]=useState('outline');
  const detectionRequest=useRef(0);
  const [outline,setOutline]=useState<{x:number;y:number}[]>([]),[surveyRevision,setSurveyRevision]=useState(0);
  const [targetSolutions,setTargetSolutions]=useState<TargetSolution[]>([]),[solvedProject,setSolvedProject]=useState('');
  const [coords,setCoords]=useState(''),[width,setWidth]=useState(0),[depth,setDepth]=useState(0),[inventoryFilter,setInventoryFilter]=useState('All'),[query,setQuery]=useState('');
  const importRef=useRef<HTMLInputElement>(null),backupRef=useRef<HTMLInputElement>(null);
  const calculation=useLayoutCalculation(project);
  const concepts=useMemo(()=>calculation.concepts.map(c=>repriceConcept(c,project.brief)),[calculation.concepts,project.brief]),concept=concepts[project.selected]||concepts[0]||emptyConcept(project.brief);
  const residual=selectedResidual?.key===concept.geometryKey&&selectedResidual?.conceptId===concept.id?concept.residualPolygons?.[selectedResidual.index]:undefined;
  function assignArea(use:AreaAllocation["use"],label:string){if(calculation.pending||calculation.error||!residual)return;const reason=allocationEligibility(concept,residual,use);if(reason){setNotice(reason);return;}setPrevious(project);setProject(p=>({...p,customAreas:[...(p.customAreas||[]),{id:crypto.randomUUID().slice(0,8),conceptId:concept.id,geometryKey:concept.geometryKey!,rings:residual,use,label}]}));setSelectedResidual(null);setNotice(`${label} assigned. Areas and business case updated; professional review remains required.`);}
  const hasBoundary=project.boundary.length>=3;
  const chosen=concept?.lots.find(p=>p.id===selectedPlot&&['residential','ews','commercial'].includes(p.use));
  const rows=concept?rowSchedule(concept):[];
  const sales=concept?saleLots(concept):[],area=polygonArea(project.boundary),brief=project.brief;
  useEffect(()=>{try{const saved=localStorage.getItem('development-studio-v3');if(saved){const loaded=parseProject(saved);setProject({...loaded,access:loaded.access||emptyAccess()});setWidth(loaded.boundary.length?extent(loaded.boundary).w:0);setDepth(loaded.boundary.length?extent(loaded.boundary).h:0);}}catch{setNotice('The saved workspace could not be restored. An empty workspace is open.');}setReady(true);},[]);
  useEffect(()=>{if(!ready)return;try{localStorage.setItem('development-studio-v3',JSON.stringify(project));}catch{setNotice('Browser storage is unavailable. Download a project backup to save your work.');}},[project,ready]);
  useEffect(()=>{
    if(!compare&&!sourceOpen&&!help)return;
    focusBeforeModal.current=document.activeElement as HTMLElement;
    const dialog=document.querySelector<HTMLElement>('[role="dialog"]');
    const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select,textarea,[tabindex="0"]')||[]);
    focusable()[0]?.focus();
    function key(e:KeyboardEvent){
      if(e.key==='Escape'){setCompare(false);setSourceOpen(false);setHelp(false);}
      if(e.key==='Tab'){const list=focusable(),first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}
    }
    document.addEventListener('keydown',key);
    return()=>{document.removeEventListener('keydown',key);focusBeforeModal.current?.focus();};
  },[compare,sourceOpen,help]);
  function edit(patch:Partial<Brief>){setProject(p=>({...p,brief:{...p.brief,...patch}}));}
  async function detectBoundary(image:SurveyImage,crop?:CropBox){const request=++detectionRequest.current;setDetecting(true);try{const candidates=await suggestBoundaries(image,crop);if(request!==detectionRequest.current)return;setSuggestions(candidates);setOutline(candidates[0]?.points||[]);setNotice(candidates.length?'Suggested boundary ready. Check that it follows your land, adjust the corners, then confirm.':'No reliable closed outline found. Crop closer to the parcel and retry, or mark its corners.');}catch(error){if(request===detectionRequest.current)setNotice((error as Error).message);}finally{if(request===detectionRequest.current)setDetecting(false);}}
  function setBoundary(points:{x:number;y:number}[]){try{const boundary=validateBoundary(points);setWidth(extent(boundary).w);setDepth(extent(boundary).h);setPrevious(project);setProject(p=>({...p,boundary,access:emptyAccess(),locks:[],exclusions:[],selected:0}));setSelectedPlot('');setDrawing(false);setAccessMode(true);setStep(0);setNotice('Boundary confirmed. Tap the boundary to add your entrances. Road-facing sides are inferred automatically.');}catch(e){setNotice((e as Error).message);}}
  async function generate(){if(!siteEntrances(project.access).length){setStep(0);setAccessMode(true);setNotice('Place at least one entrance first.');return;}if(step===2&&!calculation.pending)calculation.regenerate();setStep(2);setSidebar(false);setNotice(calculation.pending||step===2?'Calculating your layouts in the background. You can keep editing the brief.':'Your five layout options are ready to compare.');}
  async function upload(file?:File){if(!file)return;setBusy(true);try{if(/\.(kml|json)$/i.test(file.name)){if(file.size>2*1024*1024)throw Error('Coordinate files must be below 2 MB.');setBoundary(parseCoordinates(await file.text(),/\.kml$/i.test(file.name)));}else{const image=await readSurvey(file);setSurvey(image);setSurveyFile(file);setPageNumber(1);setOutline([]);setSurveyRevision(v=>v+1);setStep(0);setDrawing(true);setSidebar(true);setLandArea('');setAccessMode(false);setCropping(false);await detectBoundary(image);}setProject(p=>({...p,referenceNames:[...p.referenceNames,file.name]}));}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
  async function applyCommand(){if(!command.trim())return;const text=command;setCommand('');setBusy(true);await new Promise(r=>setTimeout(r,350));setPrevious(project);const result=applyInstruction(text,brief);edit(result.patch);setMessages(v=>[...v.slice(-3),`You: ${text}`,result.explanation]);setBusy(false);}
  function selectConcept(index:number){if(project.locks.length){setNotice('Your locked footprints will remain in every concept. Check any road conflicts before approving.');}setProject(p=>({...p,selected:index}));setSelectedPlot('');}
  function freeze(){if(calculation.pending||calculation.error||!concept.id)return setNotice('Wait for the current layout calculation to finish before approving.');if(concept.checks.some(c=>c.state==='fail'))return setNotice('Resolve failed geometry and planning checks before approving this concept.');if(project.approved&&Object.values(project.inventory).some(v=>v!=='Available'))return setNotice('This approved version has held or sold inventory. Export it and resolve those statuses before replacing it.');setProject(p=>({...p,approved:{number:(p.approved?.number||0)+1,date:new Date().toISOString(),concept:structuredClone(concept),exclusions:structuredClone(p.exclusions)},inventory:{}}));setNotice('Concept approved internally. The drawing, assumptions and inventory are now frozen for your team.');setStep(4);}
  function toggleLock(lot:Lot){if(calculation.pending||calculation.error)return;setProject(p=>({...p,locks:p.locks.some(l=>l.id===lot.id)?p.locks.filter(l=>l.id!==lot.id):[...p.locks,{...lot,locked:true}]}));}
  const field=(label:string,key:keyof Brief,min=0,max=1e12,stepValue=1)=><label className="ws-field">{label}<NumberInput min={min} max={max} step={stepValue} value={brief[key] as number} onCommit={n=>edit({[key]:n})}/></label>;
  function exportPack(){const a=project.approved;if(!a)return;const common={department,version:a.number,date:a.date,project:a.concept.brief.name,disclaimer:'Internal concept. Survey, regulations and engineering require professional verification.'};const c=a.concept;
    const payload=department==='Finance'?{assumptions:c.brief,revenue:c.revenue,cost:c.cost,profit:c.profit,margin:c.margin}:department==='Sales'?{plots:saleLots(c),status:project.inventory}:department==='Approval consultant'?{checks:c.checks,boundary:c.boundary,exclusions:a.exclusions,references:project.referenceNames}:{concept:c,exclusions:a.exclusions};
    saveFile(`${department.toLowerCase().replaceAll(' ','-')}-v${a.number}.json`,JSON.stringify({...common,...payload},null,2));
  }
  const referenceButton=<button className="ws-text-button" onClick={()=>setSourceOpen(true)}><Icon name="file"/> View your reference drawing</button>;

  return <main className="ws-app" data-clarity-mask="true">
    <header className="ws-header">
      <Link href="/" className="ws-brand"><span className="ws-brand-icon"><Icon name="grid" size={20}/></span><b>VASTUCHECK<span>DEVELOPMENT STUDIO</span></b></Link>
      <div className="ws-header-divider"/><div className="ws-project-name"><strong>{brief.name}</strong><small>{hasBoundary?`${brief.locality ? brief.locality+' · ' : ''}${(area/4046.856).toFixed(2)} acres`:'Add your land to begin'}</small></div>
      <div className="ws-header-actions"><span className="ws-save-state"><i/>{ready?'Saved locally':'Opening project'}</span><Badge state="neutral">Free access</Badge><button aria-label="How to use the studio" onClick={()=>setHelp(true)}>?</button><details className="ws-project-menu"><summary>Project ⌄</summary><div><button onClick={()=>saveFile('development-studio-backup.json',JSON.stringify(project,null,2))}>Download backup</button><button onClick={()=>backupRef.current?.click()}>Restore backup</button><button onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');detectionRequest.current++;setDetecting(false);setSuggestions([]);setAccessMode(false);setCropping(false);setPrevious(project);setProject(blankProject());setSurvey(null);setSurveyFile(null);setDrawing(false);setOutline([]);setSurveyRevision(v=>v+1);setWidth(0);setDepth(0);setLandArea('');setCoords('');setMessages([]);setSelectedPlot('');setStep(0);setNotice('New project. Draw your land or upload a survey to begin.');}}>New project</button></div></details><button className="ws-primary" disabled={!hasBoundary} onClick={()=>setStep(4)}><Icon name="download"/> Export</button></div>
    </header>
    <nav className="ws-workflow" aria-label="Development workflow">{steps.map((label,i)=><button key={label} disabled={i>0&&(!hasBoundary||!siteEntrances(project.access).length)} className={step===i?'active':''} onClick={()=>{setStep(i);setSidebar(false);}}><span>{i+1}</span>{label}{i<4&&<b>›</b>}</button>)}</nav>
    {notice&&<div className="ws-notice" role="status"><Icon name="check"/><span>{notice}</span><button aria-label="Dismiss message" onClick={()=>setNotice('')}><Icon name="close" size={14}/></button></div>}
    {calculation.pending&&<div className="ws-notice" role="status">Updating layouts in the background. You can keep editing; the drawing and geometry figures show the previous calculation until ready.</div>}
    {calculation.error&&<div className="ws-notice error" role="alert">{calculation.error}</div>}
    <input ref={importRef} type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.kml,.json,.dwg,.dxf" hidden onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/>
    <input ref={backupRef} type="file" accept=".json" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error('Backup must be smaller than 5 MB.');setProject(parseProject(await f.text()));setNotice('Project restored. Reattach survey files if you need their tracing underlay.');}catch(error){setNotice((error as Error).message);}e.target.value='';}}/>

    {step===1&&hasBoundary&&<DevelopmentBrief project={project} onChange={setProject} onGenerate={()=>void generate()} busy={busy} onBack={()=>{setStep(0);setAccessMode(true);}}/>}
    {step<3&&step!==1&&concept&&<div className="ws-workbench">
      <button className="ws-mobile-brief" onClick={()=>setSidebar(!sidebar)}><Icon name="settings"/>{sidebar?'Close settings':'Site & design settings'}</button>
      <aside className={`ws-sidebar ${sidebar?'open':''}`}>
        <div className="ws-panel-heading"><span className="ws-eyebrow">{step===0?'START WITH THE LAND':step===1?'DEFINE THE DEVELOPMENT':'DESIGN CONTROLS'}</span><h1>{step===0?'Bring in your site.':step===1?'What should this land become?':'Shape your layout.'}</h1><p>{step===0?'Upload an outline or draw your land. Enter the total area and we handle the scale.':step===1?'Set the plot sizes, access and shared spaces your project needs.':'Adjust the brief or tell the assistant what to change. Every concept recalculates.'}</p></div>
        {step===0?<>
          <label className="ws-field">What are you uploading?<select value={uploadKind} onChange={e=>setUploadKind(e.target.value)}><option value="outline">Boundary-only drawing (recommended)</option><option value="full">Full layout / approval drawing</option></select></label><p className="ws-helper">{uploadKind==='full'?'Crop to your parcel after upload. Labels, internal plots and title blocks can create uncertain outlines.':'Use a clear, closed outer boundary on a plain background. Every suggestion needs your review.'}</p>
          <button className="ws-upload" onClick={()=>importRef.current?.click()}><Icon name="upload" size={26}/><b>{survey?'Replace survey file':'Upload a survey or site plan'}</b><span>PDF, image, KML or coordinates</span></button>
          {survey&&<div className="ws-survey-status"><Icon name="file"/><div><b>{survey.name}</b><small>{survey.pages} page{survey.pages>1?'s':''} · rendered locally</small></div></div>}
          {survey&&<label className="ws-field">Drawing page<select value={pageNumber} onChange={async e=>{const n=Number(e.target.value);setPageNumber(n);if(surveyFile){setBusy(true);try{const image=await readSurvey(surveyFile,n);setSurvey(image);setOutline([]);setSurveyRevision(v=>v+1);setDrawing(true);setAccessMode(false);await detectBoundary(image);}catch(error){setNotice((error as Error).message);}finally{setBusy(false);}}}}>{Array.from({length:survey.pages},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>}
          {survey&&<div className="ws-detection"><b>{detecting?'Finding boundary candidates…':'Review the suggested boundary'}</b><p className="ws-helper">Suggestions are not verified survey boundaries. Check inward bends and exclude neighbouring land.</p><div className="ws-two-buttons"><button disabled={detecting} onClick={()=>void detectBoundary(survey)}>Detect again</button><button onClick={()=>{setDrawing(true);setAccessMode(false);setCropping(true);}}>Crop to parcel</button></div>{suggestions.length>0&&<label className="ws-field">Suggested outline<select defaultValue="0" onChange={e=>{setOutline(suggestions[Number(e.target.value)].points);setDrawing(true);setAccessMode(false);}}>{suggestions.map((v,i)=><option key={i} value={i}>Candidate {i+1} · {v.points.length} corners · needs review</option>)}</select></label>}<button onClick={()=>{setOutline([]);setDrawing(true);setAccessMode(false);}}>Draw instead</button></div>}
          {hasBoundary&&<button className="ws-full" onClick={()=>{setAccessMode(true);setDrawing(false);}}>Edit entrances</button>}
          <div className="ws-area-setup"><span className="ws-eyebrow">1 · HOW BIG IS YOUR LAND?</span><div className="ws-inline-fields"><label className="ws-field">Total land area<input type="number" min="0" step="any" placeholder="e.g. 3" value={landArea} onChange={e=>setLandArea(e.target.value)}/></label><label className="ws-field">Area unit<select value={areaUnit} onChange={e=>setAreaUnit(e.target.value as typeof areaUnit)}><option value="acres">Acres</option><option value="sqft">Square feet</option><option value="sqm">Square metres</option></select></label></div><p className="ws-helper">Use the gross area from your survey or land record. We calculate the drawing scale for you.</p><span className="ws-eyebrow">2 · REVIEW YOUR LAND’S OUTSIDE EDGE</span><p className="ws-helper">Check the suggested outline, or click outside corners to draw it. Drag corners to correct them; + adds a bend.</p><span className="ws-eyebrow">3 · CONFIRM YOUR BOUNDARY</span><p className="ws-helper">{outline.length} corners marked{Number(landArea)>0?` · ${landArea} ${areaUnit==='sqft'?'sq ft':areaUnit==='sqm'?'m²':'acres'}`:''}. The shape will be scaled to your total area. This does not verify survey dimensions.</p></div>
          <div className="ws-divider-label">OR ENTER THE PARCEL</div>
          <div className="ws-inline-fields"><label className="ws-field">Width (m)<input type="number" min="40" value={width||''} placeholder="Enter width" onChange={e=>setWidth(Number(e.target.value))}/></label><label className="ws-field">Depth (m)<input type="number" min="40" value={depth||''} placeholder="Enter depth" onChange={e=>setDepth(Number(e.target.value))}/></label></div><button className="ws-full" disabled={!width||!depth} onClick={()=>setBoundary([{x:0,y:0},{x:width,y:0},{x:width,y:depth},{x:0,y:depth}])}>Use rectangular boundary</button>
          <details className="ws-details"><summary>Irregular boundary coordinates</summary><textarea value={coords} onChange={e=>setCoords(e.target.value)} aria-label="Boundary coordinates" placeholder='[{"x":0,"y":0}, {"x":100,"y":0}, …]'/><button onClick={()=>{try{setBoundary(parseCoordinates(coords));}catch(e){setNotice((e as Error).message);}}}>Apply coordinates</button></details>
          <button className="ws-text-button" onClick={()=>{setAccessMode(false);setDrawing(!drawing);if(!survey&&hasBoundary){setOutline(project.boundary);setLandArea(String(area/4046.8564224));setAreaUnit('acres');}}}>Draw a boundary on the canvas</button>
          <div className="ws-reference-card"><b>A real-world layout reference</b><p>Open a reference layout privately to inspect its plots, roads and land-use statement.</p>{referenceButton}</div>
          <button className="ws-primary ws-full" disabled={!hasBoundary||!siteEntrances(project.access).length} onClick={()=>{setAccessMode(false);setStep(1);setDrawing(false);}}>Continue to development brief <Icon name="arrow"/></button>
        </>:<>
          {step===1&&<><label className="ws-field">Project name<input value={brief.name} onChange={e=>edit({name:e.target.value})}/></label><label className="ws-field">Location<input value={brief.locality} onChange={e=>edit({locality:e.target.value})}/></label><label className="ws-field">Planning authority<select value={brief.authority} onChange={e=>edit({authority:e.target.value as Brief['authority']})}><option>CMDA</option><option>DTCP</option><option>Karnataka LPA</option></select></label></>}
          <div className="ws-section-label"><Icon name="grid"/> Residential plot size <small>feet</small></div>
          <PlotMixControls brief={brief} onChange={edit}/>
          <div className="ws-section-label"><Icon name="settings"/> Roads & shared spaces</div>
          <label className="ws-field">Minimum internal road width <strong>{brief.road.toFixed(1)} m <small>({(brief.road/.3048).toFixed(0)} ft)</small></strong><input type="range" min="6" max={brief.roadMax} step=".5" value={brief.road} onChange={e=>edit({road:Number(e.target.value),roadMax:Math.max(brief.roadMax,Number(e.target.value))})}/><span className="ws-range-labels"><span>6 m</span><span>{brief.roadMax} m maximum</span></span></label>
          <div className="ws-inline-fields"><label className="ws-field">Park location<select value={brief.park} onChange={e=>edit({park:e.target.value as Brief['park']})}><option value="auto">Automatic · optimize layout</option><option value="central">Prefer central green</option><option value="north">Upper part of drawing</option><option value="south">Lower part of drawing</option></select></label>{field('Open space target (%)','parkPercent',5,25)}</div>
          <label className="ws-toggle"><span>Commercial sites at entrance<small>Indicative use; authority review required</small></span><input type="checkbox" checked={brief.commercial} onChange={e=>edit({commercial:e.target.checked})}/></label>
          {step===1&&<>{field('EWS share of residential plots (%)','ewsPercent',0,30)}<details className="ws-details"><summary>Protected areas & constraints</summary><button onClick={()=>{setProject(p=>({...p,exclusions:[...p.exclusions,{id:String(Date.now()),x:8,y:35,w:12,h:20,label:'No-build zone',type:'no-build'}]}));}}>+ Add exclusion</button>{project.exclusions.map(z=><div className="ws-zone" key={z.id}><input aria-label="Constraint label" value={z.label} onChange={e=>setProject(p=>({...p,exclusions:p.exclusions.map(q=>q.id===z.id?{...q,label:e.target.value}:q)}))}/><select aria-label="Constraint type" value={z.type} onChange={e=>setProject(p=>({...p,exclusions:p.exclusions.map(q=>q.id===z.id?{...q,type:e.target.value as typeof z.type}:q)}))}><option value="no-build">No-build / easement</option><option value="water">Water / channel</option><option value="structure">Existing structure</option></select><div className="ws-inline-fields">{(['x','y','w','h'] as const).map(key=><label key={key}>{key} (m)<input type="number" min={key==='w'||key==='h'?1:0} value={z[key]} onChange={e=>setProject(p=>({...p,exclusions:p.exclusions.map(q=>q.id===z.id?{...q,[key]:Math.max(key==='w'||key==='h'?1:0,Number(e.target.value))}:q)}))}/></label>)}</div><button onClick={()=>setProject(p=>({...p,exclusions:p.exclusions.filter(q=>q.id!==z.id)}))}>Remove</button></div>)}</details></>}
          {step===2&&<div className="ws-assistant"><div className="ws-section-label"><Icon name="wand"/> Design assistant <Badge state="neutral">Local</Badge></div><form onSubmit={e=>{e.preventDefault();void applyCommand();}}><textarea aria-label="Design instruction" value={command} onChange={e=>setCommand(e.target.value)} placeholder="Use 30×50 plots and a 12 m road…"/><button className="ws-primary ws-full" disabled={busy||!command.trim()}>Apply to layout <Icon name="arrow"/></button></form><div className="ws-prompt-chips">{['More plots','12 m road','15% open space'].map(t=><button key={t} onClick={()=>setCommand(t)}>{t}</button>)}</div><div className="ws-conversation" aria-live="polite">{messages.map((m,i)=><p key={i}>{m}</p>)}</div>{previous&&<button className="ws-text-button" onClick={()=>{setProject(previous);setPrevious(null);setNotice('Previous design restored.');}}><Icon name="undo"/> Undo last change</button>}</div>}
          <button className="ws-primary ws-full" disabled={busy} onClick={generate}><Icon name="wand"/>{busy?'Exploring layouts…':step===1?'Generate 5 layout options':'Regenerate options'}</button>
          <details className="ws-details"><summary>Company planning standards</summary><p className="ws-helper">Save explicit preferences for future projects.</p><button onClick={()=>{try{localStorage.setItem('development-standards-v2',JSON.stringify({plotMix:brief.plotMix,allowExtraSizes:brief.allowExtraSizes,objective:brief.objective,extendableRoads:brief.extendableRoads,roadMax:brief.roadMax,roadStyle:brief.roadStyle,allowOdd:brief.allowOdd,maxOddPercent:brief.maxOddPercent,road:brief.road,frontage:brief.frontage,depth:brief.depth,park:brief.park,parkPercent:brief.parkPercent,commercial:brief.commercial,ewsPercent:brief.ewsPercent}));setNotice('Company planning preferences saved.');}catch{setNotice('Browser storage unavailable. Download a project backup.');}}}>Save current standards</button><button onClick={()=>{try{const raw=localStorage.getItem('development-standards-v2');if(!raw)return setNotice('Save your standards first.');const p={...project,brief:{...brief,...JSON.parse(raw)}};setProject(parseProject(JSON.stringify(p)));setNotice('Company standards applied.');}catch{setNotice('Saved standards could not be read.');}}}>Apply standards</button></details>
        </>}
        <div className="ws-sidebar-note">Concept planning · {brief.authority}<br/>Regulatory assumptions need professional verification.</div>
      </aside>
      <section className="ws-drawing-workspace">{step===0&&accessMode&&hasBoundary?<><AccessCanvas boundary={project.boundary} access={project.access} onChange={access=>setProject(p=>({...p,access}))}/><div className="ws-site-summary"><b>{(area/4046.8564224).toFixed(2)} acres · Boundary confirmed</b><p>{siteEntrances(project.access).length} entrance(s) · {project.access?.northAngle==null?'North unknown':`North set to ${project.access.northAngle}°`}</p><button className="ws-primary" disabled={!siteEntrances(project.access).length} onClick={()=>{setAccessMode(false);setStep(1);}}>Confirm site & continue</button></div></>:<>
        <div className="ws-drawing-header"><div><h2>{!hasBoundary?'Your land':step===0&&drawing?'Survey & boundary':step===1?'Live design preview':concept.name}</h2><p>{!hasBoundary?'Draw a boundary or upload your survey to start.':step===0&&drawing?'Enter your land area, mark its corners, then confirm.':`Concept ${concept.id} · ${sales.length} plots · ${concept.efficiency.toFixed(1)}% saleable`}</p></div>{hasBoundary&&<div className="ws-drawing-actions"><div className="ws-view-toggle"><button className={!technical?'active':''} onClick={()=>setTechnical(false)}>Masterplan</button><button className={technical?'active':''} onClick={()=>{setTechnical(true);setLayers(v=>({...v,dimensions:true}));}}>Technical</button></div><details className="ws-layer-menu"><summary><Icon name="layers"/> Layers</summary><div>{Object.entries(layers).map(([key,value])=><label key={key}><input type="checkbox" checked={value} onChange={e=>setLayers(v=>({...v,[key]:e.target.checked}))}/>{key}</label>)}</div></details><button onClick={()=>setCompare(true)}><Icon name="compare"/> Compare</button></div>}</div>
        <div className="ws-plan-area">{!hasBoundary&&!drawing?<div className="ws-empty-start"><Icon name="grid" size={36}/><h2>Start with your land.</h2><p>Your canvas is empty. Choose how you want to add your site.</p><div><button className="ws-primary" onClick={()=>{setDrawing(true);}}>Draw land boundary</button><button onClick={()=>importRef.current?.click()}>Upload survey</button></div><small>You can also enter width and depth in the site settings.</small></div>:<PlanCanvas key={`${survey?.name||'blank'}-${surveyRevision}`} concept={concept} exclusions={project.exclusions} selected={selectedPlot} onSelect={p=>{setSelectedPlot(p.id);setSelectedResidual(null);}} selectedResidual={residual?selectedResidual?.index:null} onResidualSelect={index=>{setSelectedPlot('');setSelectedResidual({key:concept.geometryKey!,conceptId:concept.id,index});}} layers={layers} technical={technical} draw={drawing} survey={survey} cropping={cropping} onCrop={crop=>{setCropping(false);if(survey)void detectBoundary(survey,crop);}} onCancelCrop={()=>setCropping(false)} points={outline} onPointsChange={setOutline} canConfirm={Number(landArea)>0} areaLabel={Number(landArea)>0?`${landArea} ${areaUnit==='sqft'?'sq ft':areaUnit==='sqm'?'m²':'acres'}`:''} onDraw={points=>{try{setBoundary(boundaryFromArea(points,Number(landArea),areaUnit));}catch(error){setNotice((error as Error).message);}}}/>}
          {residual&&!drawing&&<aside className="ws-plot-inspector ws-residual-inspector"><button className="ws-inspector-close" aria-label="Close area details" onClick={()=>setSelectedResidual(null)}><Icon name="close" size={14}/></button><span className="ws-eyebrow">UNALLOCATED LAND</span><h3>Give this space a purpose.</h3><strong className="ws-plot-area">{Math.round(residualArea(residual)*SQFT).toLocaleString()} <small>sq ft</small></strong><p className="ws-helper">Assign this whole pocket. Existing plots, roads and parks stay in place.</p><div className="ws-allocation-options">{([['infrastructure','Utility area'],['infrastructure','Transformer site'],['residential','Residential plot'],['commercial','Commercial site']] as const).map(([use,label])=>{const reason=allocationEligibility(concept,residual,use);return <div key={label}><button className="ws-full" disabled={!!reason} onClick={()=>assignArea(use,label)}>{label}</button>{reason&&<small>{reason}</small>}</div>;})}</div><p className="ws-helper">Transformer clearances, service access and commercial permissions require specialist review. Utility assignments use a provisional cost allowance of ₹10,000/m², not an equipment quote.</p></aside>}
          {chosen&&!drawing&&<aside className="ws-plot-inspector"><button className="ws-inspector-close" aria-label="Close plot details" onClick={()=>setSelectedPlot('')}><Icon name="close" size={14}/></button><span className="ws-eyebrow">PLOT DETAILS</span><h3>Plot {chosen.id}</h3><Badge state="neutral">{chosen.use}</Badge><strong className="ws-plot-area">{Math.round(chosen.area*SQFT).toLocaleString()} <small>sq ft</small></strong><dl><div><dt>Dimensions</dt><dd>{chosen.shape==='irregular'?'Irregular polygon':`${(chosen.w/.3048).toFixed(0)} × ${(chosen.h/.3048).toFixed(0)} ft`}</dd></div><div><dt>Route to entrance</dt><dd>{chosen.exitAccess?"Connected by road":"Not verified"}</dd></div><div><dt>Facing</dt><dd>{chosen.facing}</dd></div><div><dt>Corner plot</dt><dd>{chosen.corner?'Yes':'No'}</dd></div><div><dt>Price premium</dt><dd>{chosen.premium}%</dd></div><div><dt>Shape discount</dt><dd>{chosen.discount||0}%</dd></div><div><dt>Indicative value</dt><dd>{currency(plotValue(chosen,concept.brief))}</dd></div></dl><button disabled={!!chosen.allocationId} className="ws-full" onClick={()=>toggleLock(chosen)}><Icon name="lock"/>{project.locks.some(p=>p.id===chosen.id)?'Unlock footprint':'Keep this plot unchanged'}</button><small>Locked footprints stay fixed during regeneration. Conflicting roads will be flagged.</small></aside>}
          {(busy||detecting||(calculation.pending&&!drawing))&&<div className="ws-generating" role="status"><span className="ws-spinner"/><strong>{detecting?'Finding possible boundaries':'Exploring the possibilities'}</strong><span>{detecting?'Analysing the drawing locally · Please review the suggested outline':'Fitting plots · Allocating open space · Evaluating costs'}</span></div>}
        </div>
        {hasBoundary&&<><div className="ws-quality-summary"><b>{concept.regularCount||0} regular plots</b><span>{sales.filter(p=>p.exitAccess).length}/{sales.length} plots connected to an entrance</span>{!!concept.accessRoads&&<span>{concept.accessRoads} connecting road(s) added</span>}<span>{concept.irregularCount||0} irregular edge plots</span><span>{concept.roadStyleApplied||"Straight streets"} · {concept.brief.road} m main · {concept.secondaryRoadWidth??concept.brief.road} m secondary roads</span><span>{(100-concept.unallocated/concept.area*100).toFixed(1)}% land allocated</span><span>{concept.unallocated.toFixed(0)} m² unallocated ({(concept.unallocated/concept.area*100).toFixed(1)}%)</span><button onClick={()=>setStep(1)}>Edit requirements</button></div>{!calculation.pending&&<ConceptExplanation concept={concept} brief={brief}/>}{brief.mixedRows!==false&&rows.length>0&&<details className="ws-details ws-row-schedule"><summary>Plot sizes by row · {rows.length} rows</summary><p className="ws-helper">One repeated size per row. Adjustments are reserved for row ends and irregular boundary plots. Dimensions below are in feet; final dimensions remain visible on each plot.</p><table><thead><tr><th>Row</th><th>Repeated size (ft)</th><th>Same size</th><th>Adjusted</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.width.toFixed(1)} × {r.depth.toFixed(1)}</td><td>{r.repeated}</td><td>{r.adjusted}</td></tr>)}</tbody></table></details>}{(project.customAreas||[]).filter(a=>a.conceptId===concept.id).length>0&&<details className="ws-details" open><summary>Assigned spaces</summary>{(project.customAreas||[]).filter(a=>a.conceptId===concept.id).map(a=><div className="ws-assigned-space" key={a.id}><span><b>{a.label}</b> · {Math.round(residualArea(a.rings)*SQFT)} sq ft<small>{concept.lots.some(l=>l.allocationId===a.id)?'Included in this concept':'Inactive — layout changed; select a new grey area'}</small></span><button onClick={()=>{setSelectedResidual(null);setPrevious(project);setProject(p=>({...p,customAreas:p.customAreas?.filter(q=>q.id!==a.id)}));setNotice("Area returned to unallocated land.");}}>Return to unallocated</button></div>)}</details>}<p className="ws-helper">Click a grey pocket on the plan to assign a utility, transformer, residential or commercial use. Remaining land is excluded from sales. Review residual pockets against frontage, shape limits and your irregular-plot allowance.</p><div className="ws-concept-strip">{concepts.map((c,i)=><button key={c.id} className={project.selected===i?'active':''} onClick={()=>selectConcept(i)}><MiniPlan concept={c}/><div><span>OPTION {c.id}{project.selected===i&&<i>Selected</i>}</span><b>{c.name}</b><small>{saleLots(c).length} plots <em>·</em> {c.efficiency.toFixed(1)}% saleable</small></div></button>)}</div>
        <div className="ws-yield-bar"><Metric label="Saleable plots" value={String(sales.length)}/><Metric label="Saleable area" value={`${concept.efficiency.toFixed(1)}%`}/><Metric label="Expected revenue" value={currency(concept.revenue)}/><Metric label="Development cost" value={currency(concept.infra)}/><Metric label="Project margin" value={`${concept.margin.toFixed(1)}%`}/><button className="ws-primary" onClick={()=>setStep(3)}>Review business case <Icon name="arrow"/></button></div></>}
      </>}</section>
    </div>}

    {step===3&&concept&&<section className="ws-review-page"><div className="ws-page-heading"><div><span className="ws-eyebrow">MAKE THE DEVELOPMENT DECISION</span><h1>The plan. The numbers. The trade-offs.</h1><p>Concept {concept.id} · {concept.name} · All numbers respond to your assumptions.</p></div><button onClick={()=>setCompare(true)}><Icon name="compare"/> Compare five concepts</button></div><div className="ws-report-tabs">{['Financials','Planning checks','Infrastructure','Acquisition & solver'].map(t=><button className={reportTab===t?'active':''} key={t} onClick={()=>setReportTab(t)}>{t}</button>)}</div>
      <div className="ws-report-metrics"><Metric label="Gross development value" value={currency(concept.revenue)} note="Includes residential, EWS and commercial assumptions"/><Metric label="Total project cost" value={currency(concept.cost)} note="Land + development + consultants + marketing"/><Metric label="Project profit" value={currency(concept.profit)} note="Before financing and tax"/><Metric label="Profit margin" value={`${concept.margin.toFixed(1)}%`} note={`Company target: ${brief.targetMargin}%`}/></div>
      {reportTab==='Financials'&&<div className="ws-report-grid"><article className="ws-card"><h2>Commercial assumptions</h2><div className="ws-two-col">{field(brief.landBasis==='acre'?'Land price (₹ / acre)':brief.landBasis==='sqft'?'Land price (₹ / sq ft)':'Total land acquisition cost (₹)','land',0,1e12,100000)}{field('Base selling price (₹ / sq ft)','price',0,1e7,100)}{field('Approvals & consultants (₹)','fees',0,1e10,100000)}{field('Marketing (% of revenue)','marketing',0,30,.5)}</div><p className="ws-helper">Commercial plots use 1.2× base price; EWS plots use 0.8×. Corner and park proximity premiums are added; irregular plots use your configured discount. Financing, tax and phasing are not separately modeled.</p><h3>Price sensitivity</h3><table><thead><tr><th>Selling price</th><th>Revenue</th><th>Profit margin</th></tr></thead><tbody>{[-10,-5,0,5,10].map(n=>{const r=concept.revenue*(1+n/100),cost=landCost(brief,concept.area)+concept.infra+brief.fees+r*brief.marketing/100;return <tr key={n}><td>{n>0?'+':''}{n}%</td><td>{currency(r)}</td><td>{r?((r-cost)/r*100).toFixed(1):0}%</td></tr>;})}</tbody></table><button disabled={calculation.pending||!!calculation.error} onClick={()=>saveFile('concept-feasibility.csv',financeCSV(concepts),'text/csv')}><Icon name="download"/> Download feasibility CSV</button></article><article className="ws-card"><h2>Land-use statement</h2><p>Every square metre accounted for.</p>{[['Residential & EWS',concept.residential,'#dfd7bb'],['Commercial',concept.commercialArea,'#d9b78f'],['Roads',concept.roadsArea,'#c5cfcb'],['Park / OSR',concept.parkArea,'#b5d29e'],['Public use, clubhouse & amenities',concept.publicArea,'#c7bfde'],['Protected land / buffers',concept.protectedArea||0,'#d2e4ec'],['Remaining land to resolve',concept.unallocated,'#e5e8df']].map(([label,value,color])=><div className="ws-area-row" key={label}><div><span>{label}</span><b>{Number(value).toLocaleString(undefined,{maximumFractionDigits:0})} m² <small>{(Number(value)/concept.area*100).toFixed(1)}%</small></b></div><div className="ws-area-track"><i style={{width:`${Math.max(0,Number(value)/concept.area*100)}%`,background:String(color)}}/></div></div>)}<div className="ws-area-total"><b>Total parcel</b><strong>{concept.area.toLocaleString()} m²</strong></div></article></div>}
      {reportTab==='Planning checks'&&<article className="ws-card"><div className="ws-card-heading"><div><h2>Design checks & authority review</h2><p>India / {brief.authority==='Karnataka LPA'?'Karnataka':'Tamil Nadu'} / {brief.authority} / Residential layout / {CMDA_BASELINE.id}</p></div><Badge state="review">Professional review required</Badge></div><div className="ws-rule-note">Geometry checks are calculated. CMDA/DTCP checks use the linked 2019 + 2020 source baseline; later amendments and site conditions need verification. An approval shown on an imported reference drawing does not transfer to this site.</div><p><a href={CMDA_BASELINE.source} target="_blank" rel="noreferrer">TNCDBR 2019 · Rule 47</a> · <a href={CMDA_BASELINE.amendment} target="_blank" rel="noreferrer">G.O.16 (2020) amendments</a></p><div className="ws-table-scroll"><table><thead><tr><th>Check</th><th>Result</th><th>Current design</th><th>Requirement / source</th></tr></thead><tbody>{concept.checks.map(c=><tr key={c.name}><td><b>{c.name}</b></td><td><Badge state={c.state}>{c.state}</Badge></td><td>{c.actual}</td><td>{c.requirement}<small className="ws-cell-note">{c.source}</small></td></tr>)}</tbody></table></div>{referenceButton}</article>}
      {reportTab==='Infrastructure'&&<div className="ws-report-grid"><article className="ws-card"><h2>Infrastructure quantities</h2><p>Concept estimates tied to this road network.</p><table><thead><tr><th>Item</th><th>Quantity</th><th>Cost</th></tr></thead><tbody>{[['Road construction',`${concept.roadsArea.toFixed(0)} m²`,concept.roadsArea*brief.roadRate],['Stormwater drainage',`${concept.roadLength.toFixed(0)} m`,concept.roadLength*1800],['Water & sewer',`${concept.roadLength.toFixed(0)} m`,concept.roadLength*2400],['Electrical network',`${concept.roadLength.toFixed(0)} m`,concept.roadLength*1600],['Street lights',`${Math.ceil(concept.roadLength/30)} units`,Math.ceil(concept.roadLength/30)*35000],['Landscaping',`${concept.parkArea.toFixed(0)} m²`,concept.parkArea*650],['Public facilities',`${concept.publicArea.toFixed(0)} m²`,concept.publicArea*10000],['Earthwork allowance',`${concept.earthwork.toFixed(0)} m³`,concept.earthwork*brief.earthRate]].map(([label,q,value])=><tr key={label}><td>{label}</td><td>{q}</td><td>{currency(Number(value))}</td></tr>)}</tbody></table><div className="ws-area-total"><b>Total development cost</b><strong>{currency(concept.infra)}</strong></div></article><article className="ws-card"><h2>Terrain & construction assumptions</h2>{field('Road construction (₹ / m²)','roadRate',0,1e7,100)}{field('Assumed site slope (%)','slope',0,30,.1)}{field('Earthwork rate (₹ / m³)','earthRate',0,1e6,10)}<div className="ws-terrain-diagram"><svg viewBox="0 0 400 130" aria-label="Illustrative terrain section"><path d={`M0 100L400 ${100-brief.slope*2}V130H0Z`} fill="#d6e4cd"/><path d={`M0 100L400 ${100-brief.slope*2}`} fill="none" stroke="#73965f" strokeWidth="2"/><path d="M0 80H400" stroke="#ae9470" strokeDasharray="6 6"/><text x="12" y="25" fill="#899782" fontSize="11">ASSUMED SECTION · NOT A TOPOGRAPHIC SURVEY</text></svg></div><p className="ws-helper">Volume = area × slope fraction × 0.35 m allowance. Actual contours, cut/fill balance, water flow and road gradients need a surveyed elevation model and engineering design.</p></article></div>}
      {reportTab==='Acquisition & solver'&&<div className="ws-report-grid"><article className="ws-card"><h2>Set the deal thresholds</h2>{field('Minimum plot count','minPlots',1,10000)}{field('Minimum project revenue (₹)','revenueTarget',0,1e12,1000000)}{field('Maximum infrastructure cost (₹)','infraCap',0,1e12,1000000)}{field('Target margin (%)','targetMargin',0,90)}<div className="ws-acquisition"><span>Residual land budget</span><strong>{currency(concept.maxLand)}</strong><Badge state={landCost(brief,concept.area)<=concept.maxLand?'pass':'review'}>{landCost(brief,concept.area)<=concept.maxLand?'Within your target':'Above your target land budget'}</Badge></div><p className="ws-helper">Revenue less target profit, marketing, infrastructure and consultant costs. A configurable underwriting threshold, not a purchase recommendation.</p></article><article className="ws-card"><h2>Which concepts meet your targets?</h2><p>Search your selected plot sizes and road-width range, keeping your park preference and plot-mix requirements.</p><button className="ws-primary" disabled={busy} onClick={async()=>{setBusy(true);await new Promise(r=>setTimeout(r,100));try{setTargetSolutions(await planningJob<TargetSolution[]>(project,'targets',new AbortController().signal));setSolvedProject(JSON.stringify(project));}catch(error){setNotice((error as Error).message);}finally{setBusy(false);}}}>{busy?'Searching layouts…':'Find layouts for my targets'}</button>{solvedProject===JSON.stringify(project)&&targetSolutions.map((r,i)=><div className="ws-solver-row" key={`solution-${i}`}><MiniPlan concept={r.concept}/><div><b>Solution {i+1} · {r.project.brief.frontage} × {r.project.brief.depth} ft</b><p>{saleLots(r.concept).length} plots · {currency(r.concept.revenue)} · {r.concept.margin.toFixed(1)}% margin</p><small>{r.unmet.length?`Unmet: ${r.unmet.join(', ')}`:'Meets your configured targets; professional review still required.'}</small></div><button onClick={()=>{setPrevious(project);setProject(r.project);setStep(2);setSelectedPlot('');}}>Use</button></div>)}<h3>Current five concepts</h3>{[...concepts].sort((a,b)=>b.profit-a.profit).map(c=>{const unmet=[saleLots(c).length<brief.minPlots?'Plot count':'',c.revenue<brief.revenueTarget?'Revenue':'',c.infra>brief.infraCap?'Infrastructure budget':'',c.margin<brief.targetMargin?'Margin':'',c.checks.some(v=>v.state==='fail')?'Design checks':''].filter(Boolean);return <div className="ws-solver-row" key={c.id}><MiniPlan concept={c}/><div><b>{c.id} · {c.name}</b><p>{saleLots(c).length} plots · {currency(c.revenue)} · {c.margin.toFixed(1)}% margin</p><small>{unmet.length?`Outside targets: ${unmet.join(', ')}`:'Meets configured targets; authority review still required.'}</small></div><button onClick={()=>{selectConcept(concepts.findIndex(v=>v.id===c.id));setStep(2);}}>View</button></div>;})}</article></div>}
      <div className="ws-review-next"><span>Ready to take this concept to your team?</span><button className="ws-primary" disabled={!hasBoundary} onClick={()=>setStep(4)}>Prepare handoff <Icon name="arrow"/></button></div>
    </section>}

    {step===4&&concept&&<section className="ws-review-page"><div className="ws-page-heading"><div><span className="ws-eyebrow">FROM A CONCEPT TO A SHARED DECISION</span><h1>Give every team a clear starting point.</h1><p>Freeze a version, hand over the drawing and keep the plot inventory connected.</p></div><button onClick={()=>setStep(2)}>Back to masterplan</button></div><div className="ws-report-tabs">{['Deliverables','Sales inventory'].map(t=><button key={t} className={handoffTab===t?'active':''} onClick={()=>setHandoffTab(t)}>{t}</button>)}</div>
      {handoffTab==='Deliverables'?<div className="ws-handoff-grid"><article className="ws-card ws-approval-card"><MiniPlan concept={project.approved?.concept||concept}/><span className="ws-eyebrow">{project.approved?'FROZEN INTERNAL CONCEPT':'CURRENT WORKING CONCEPT'}</span><h2>Concept {project.approved?.concept.id||concept.id} · {project.approved?.concept.name||concept.name}</h2><p>{project.approved?`Version ${project.approved.number} · ${new Date(project.approved.date).toLocaleDateString()}`:'Review the planning checks before you approve this concept.'}</p><button className="ws-primary ws-full" disabled={concept.checks.some(c=>c.state==='fail')} onClick={freeze}><Icon name="check"/>{project.approved?'Approve current draft as new version':'Approve internal concept'}</button><p className="ws-helper">Internal approval freezes the geometry and assumptions. It is not statutory approval. Held or sold plots protect the existing inventory from replacement.</p></article><article className="ws-card"><div className="ws-card-heading"><div><h2>A purpose-built handoff</h2><p>{project.approved?'Exports use the approved snapshot, even if the working design changes.':'Approve a concept to enable the department deliverables.'}</p></div><select aria-label="Handoff department" value={department} onChange={e=>setDepartment(e.target.value)}>{departments.map(d=><option key={d}>{d}</option>)}</select></div><div className="ws-export-grid">{[
        ['Technical site plan','Dimensioned masterplan, land-use summary and review notes.','PDF',()=>window.print()],
        ['CAD drawing','Boundary, numbered plots, road surfaces and reserved spaces.','DXF',()=>project.approved&&saveFile('concept-site-plan.dxf',cadDXF(project.approved.concept,project.approved.exclusions),'application/dxf')],
        ['Plot inventory','Plot sizes, facing, corner attributes, indicative prices and status.','CSV',()=>project.approved&&saveFile('plot-inventory.csv',inventoryCSV(project.approved.concept,project.inventory),'text/csv')],
        ['Financial feasibility','Project economics and assumptions for the frozen concept.','CSV',()=>project.approved&&saveFile('approved-feasibility.csv',financeCSV([project.approved.concept]),'text/csv')],
        [`${department} pack`,'A structured package of the information this team needs.','JSON',exportPack],
        ['Complete project backup','Editable project, draft settings, frozen concept and inventory.','JSON',()=>saveFile('development-project.json',JSON.stringify(project,null,2))],
      ].map(([title,desc,type,action])=><button key={String(title)} disabled={!project.approved} onClick={action as ()=>void}><span className="ws-export-type">{String(type)}</span><h3>{String(title)}</h3><p>{String(desc)}</p><span className="ws-export-action">{type==='PDF'?'Print / save PDF':'Download'} <Icon name="download" size={14}/></span></button>)}</div></article></div>:<article className="ws-card"><div className="ws-card-heading"><div><h2>Sales inventory</h2><p>{project.approved?`Concept ${project.approved.concept.id} · Version ${project.approved.number} · ${saleLots(project.approved.concept).length} plots`:'Approve an internal concept to create its inventory.'}</p></div>{project.approved&&<button onClick={()=>saveFile('plot-inventory.csv',inventoryCSV(project.approved!.concept,project.inventory),'text/csv')}>Export CSV</button>}</div>{project.approved?<><div className="ws-inventory-controls"><input aria-label="Search plot" placeholder="Search plot number…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter plot status" value={inventoryFilter} onChange={e=>setInventoryFilter(e.target.value)}>{['All','Available','Held','Sold'].map(v=><option key={v}>{v}</option>)}</select></div><div className="ws-table-scroll"><table><thead><tr>{['Plot','Use','Shape','Area (sq ft)','Facing','Corner','Premium','Discount','Status'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{saleLots(project.approved.concept).filter(p=>p.id.includes(query)&&(inventoryFilter==='All'||(project.inventory[p.id]||'Available')===inventoryFilter)).map(p=><tr key={p.id}><td><b>{p.id}</b></td><td>{p.use}</td><td>{p.shape||'regular'}</td><td>{(p.area*SQFT).toFixed(0)}</td><td>{p.facing}</td><td>{p.corner?'Yes':'—'}</td><td>{p.premium}%</td><td>{p.discount||0}%</td><td><select aria-label={`Plot ${p.id} status`} value={project.inventory[p.id]||'Available'} onChange={e=>setProject(v=>({...v,inventory:{...v.inventory,[p.id]:e.target.value as 'Available'|'Held'|'Sold'}}))}>{['Available','Held','Sold'].map(v=><option key={v}>{v}</option>)}</select></td></tr>)}</tbody></table></div></>:<div className="ws-empty"><Icon name="grid" size={36}/><h3>Your approved plan becomes your inventory.</h3><button onClick={()=>setHandoffTab('Deliverables')}>Approve a concept first</button></div>}</article>}
    </section>}

    {compare&&<div className="ws-modal-backdrop"><section className="ws-modal ws-comparison" role="dialog" aria-modal="true" aria-label="Compare development concepts"><div className="ws-modal-heading"><div><span className="ws-eyebrow">SAME LAND. FIVE DIFFERENT BUSINESS CASES.</span><h2>Choose the trade-off that works for you.</h2></div><button aria-label="Close comparison" onClick={()=>setCompare(false)}><Icon name="close"/></button></div><div className="ws-compare-grid">{concepts.map((c,i)=><article className={project.selected===i?'selected':''} key={c.id}><span className="ws-eyebrow">OPTION {c.id}</span><h3>{c.name}</h3><p>{c.strategy}</p><MiniPlan concept={c}/><dl>{[['Requested plots missing',plotMixReport(c).shortfall],['Additional sizes',plotMixReport(c).extras.length],['Regular plots',c.regularCount||0],['Irregular plots',c.irregularCount||0],['Remaining land',`${c.unallocated.toFixed(0)} m²`],['Saleable land',`${c.efficiency.toFixed(1)}%`],['Road area',`${(c.roadsArea/c.area*100).toFixed(1)}%`],['Revenue',currency(c.revenue)],['Infrastructure',currency(c.infra)],['Project margin',`${c.margin.toFixed(1)}%`]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><Badge state={c.checks.some(v=>v.state==='fail')?'fail':'review'}>{c.checks.some(v=>v.state==='fail')?'Design issues':'Authority review pending'}</Badge><button className={project.selected===i?'ws-primary':''} onClick={()=>{selectConcept(i);setCompare(false);setStep(2);}}>{project.selected===i?'Continue with this option':'Explore option '+c.id}<Icon name="arrow" size={14}/></button></article>)}</div></section></div>}
    {sourceOpen&&<div className="ws-modal-backdrop"><section className="ws-modal ws-reference-modal" role="dialog" aria-modal="true" aria-label="Reference approval drawing"><div className="ws-modal-heading"><div><span className="ws-eyebrow">USER-SUPPLIED REFERENCE · NOT A GENERATED DESIGN</span><h2>{survey?.name||'Your reference layout'}</h2><p>View the actual survey locally. The file stays in your browser and is not uploaded to a server.</p></div><button aria-label="Close reference drawing" onClick={()=>setSourceOpen(false)}><Icon name="close"/></button></div><div className="ws-reference-image">{survey?<Image src={survey.url} width={survey.width} height={survey.height} alt="Your privately imported survey drawing" unoptimized/>:<div className="ws-empty"><Icon name="file" size={36}/><h3>Open your survey or reference PDF</h3><p>Read it here, enter the land area and mark the outside boundary.</p><button className="ws-primary" onClick={()=>{setSourceOpen(false);setStep(0);importRef.current?.click();}}>Choose a local file</button></div>}</div><div className="ws-reference-footer"><span>Reference documents inform planning. Approvals and conditions belong to their original projects.</span><button onClick={()=>{setSourceOpen(false);setStep(0);}}>Back to site setup</button></div></section></div>}
    {help&&<div className="ws-modal-backdrop"><section className="ws-modal ws-help" role="dialog" aria-modal="true" aria-label="Studio quick guide"><div className="ws-modal-heading"><h2>From land to a decision.</h2><button aria-label="Close guide" onClick={()=>setHelp(false)}><Icon name="close"/></button></div>{[['Bring in your site','Upload a PDF or image, enter the total area and mark the outside corners. Drag corners to adjust the outline. Or import KML / coordinate JSON.'],['Set the development brief','Choose plot sizes, road width, parks, commercial space and the authority.'],['Explore five layouts','Compare the plans, inspect plots and lock footprints you want to keep.'],['Review the business case','Enter actual costs and sale prices. Check area allocation and unresolved planning requirements.'],['Freeze and hand over','Approve an internal version, download department files and manage the plot inventory.']].map(([title,description],i)=><div className="ws-help-step" key={title}><span>{i+1}</span><div><h3>{title}</h3><p>{description}</p></div></div>)}<button className="ws-primary ws-full" onClick={()=>{setHelp(false);setStep(0);}}>Start with my site <Icon name="arrow"/></button></section></div>}
    {project.approved&&<section className="ws-print"><h1>{project.approved.concept.brief.name}</h1><p>INTERNAL CONCEPT {project.approved.concept.id} · VERSION {project.approved.number} · {project.approved.date.slice(0,10)}</p><svg viewBox={`-15 -15 ${extent(project.approved.concept.boundary).w+45} ${extent(project.approved.concept.boundary).h+55}`}><PlanDrawing concept={project.approved.concept} exclusions={project.approved.exclusions} id="print" layers={{...defaultLayers,dimensions:true}} technical/></svg><h2>Land-use statement & feasibility</h2><p>{saleLots(project.approved.concept).length} plots · {project.approved.concept.efficiency.toFixed(1)}% saleable · Revenue {currency(project.approved.concept.revenue)} · Cost {currency(project.approved.concept.cost)} · Margin {project.approved.concept.margin.toFixed(1)}%</p><table><tbody>{project.approved.concept.checks.map(c=><tr key={c.name}><td>{c.name}</td><td>{c.state}</td><td>{c.actual}</td></tr>)}</tbody></table><p>Concept drawing only. Regulatory compliance, survey accuracy, access and engineering design require licensed professionals and authority verification. Costs are indicative and exclude separately modeled financing and taxes.</p></section>}
  </main>;
}
